#version 440

#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
#if HLSLCC_ENABLE_UNIFORM_BUFFERS
#define UNITY_UNIFORM
#else
#define UNITY_UNIFORM uniform
#endif
#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
#if UNITY_SUPPORTS_UNIFORM_LOCATION
#define UNITY_LOCATION(x) layout(location = x)
#define UNITY_BINDING(x) layout(binding = x, std140)
#else
#define UNITY_LOCATION(x)
#define UNITY_BINDING(x) layout(std140)
#endif
precise vec4 u_xlat_precise_vec4;
precise ivec4 u_xlat_precise_ivec4;
precise bvec4 u_xlat_precise_bvec4;
precise uvec4 u_xlat_precise_uvec4;
layout(set = 0, binding = 0, std140) uniform CB1 {
	vec4 InvLowResolution;
	vec4 InvHighResolution;
	vec4 AdditionalParams;
};
layout(set = 0, binding = 1) uniform highp texture2D LoResDB;
layout(set = 0, binding = 2) uniform highp texture2D HiResDB;
layout(set = 0, binding = 3) uniform highp texture2D LoResAO1;
layout(set = 0, binding = 4) uniform highp texture2D HiResAO;
writeonly layout(set = 0, binding = 5, rg32f) highp uniform image2D AoResult_origX0X;
vec4 u_xlat0;
ivec4 u_xlati0;
uint u_xlatu0;
bvec2 u_xlatb0;
vec4 u_xlat1;
ivec4 u_xlati1;
uint u_xlatu1;
vec4 u_xlat2;
ivec4 u_xlati2;
vec4 u_xlat3;
uvec4 u_xlatu3;
vec4 u_xlat4;
ivec4 u_xlati4;
bvec2 u_xlatb4;
vec4 u_xlat5;
bvec2 u_xlatb5;
vec4 u_xlat6;
bvec4 u_xlatb6;
vec4 u_xlat7;
bvec2 u_xlatb7;
vec4 u_xlat8;
vec4 u_xlat9;
vec2 u_xlat10;
ivec4 u_xlati10;
vec4 u_xlat11;
vec4 u_xlat12;
vec4 u_xlat13;
vec2 u_xlat14;
vec2 u_xlat15;
ivec3 u_xlati15;
vec2 u_xlat30;
int u_xlati30;
vec2 u_xlat31;
ivec2 u_xlati31;
bvec2 u_xlatb31;
vec2 u_xlat32;
ivec2 u_xlati32;
vec2 u_xlat33;
ivec2 u_xlati33;
bvec2 u_xlatb33;
vec2 u_xlat34;
bvec2 u_xlatb34;
vec2 u_xlat35;
ivec2 u_xlati35;
bvec2 u_xlatb35;
vec2 u_xlat36;
vec2 u_xlat37;
vec2 u_xlat38;
vec2 u_xlat39;
int u_xlati45;
shared struct {
	uint value[2];
} TGSM0[256];
shared struct {
	uint value[2];
} TGSM1[256];
shared struct {
	uint value[2];
} TGSM2[256];
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
layout(set = 0, binding = 6) uniform highp  sampler samplerLoResDB;
layout(set = 0, binding = 7) uniform highp  sampler samplerHiResDB;
layout(set = 0, binding = 8) uniform highp  sampler samplerLoResAO1;
layout(set = 0, binding = 9) uniform highp  sampler samplerHiResAO;
void main()
{
    u_xlati0.x = int(gl_LocalInvocationID.x) << 1;
    u_xlati0.x = int(gl_LocalInvocationID.y) * 32 + u_xlati0.x;
    u_xlati15.xy = ivec2(gl_LocalInvocationID.xy) + ivec2(gl_GlobalInvocationID.xy);
    u_xlati15.xy = u_xlati15.xy + ivec2(int(0xFFFFFFFEu), int(0xFFFFFFFEu));
    u_xlat15.xy = vec2(u_xlati15.xy);
    u_xlat15.xy = u_xlat15.xy * InvLowResolution.xy;
    u_xlat1 = textureGather(sampler2D(LoResAO1, samplerLoResAO1), u_xlat15.xy);
    u_xlat2 = textureGather(sampler2D(LoResAO1, samplerLoResAO1), u_xlat15.xy, 1).zxwy;
    u_xlat3.xz = u_xlat1.wz;
    u_xlat3.yw = u_xlat2.zx;
    TGSM1[u_xlati0.x].value[(0 >> 2)] = floatBitsToUint(u_xlat3.x);
    TGSM1[u_xlati0.x].value[(0 >> 2) + 1] = floatBitsToUint(u_xlat3.y);
    u_xlati45 = u_xlati0.x + 1;
    TGSM1[u_xlati45].value[(0 >> 2)] = floatBitsToUint(u_xlat3.z);
    TGSM1[u_xlati45].value[(0 >> 2) + 1] = floatBitsToUint(u_xlat3.w);
    u_xlati31.xy = u_xlati0.xx + ivec2(16, 17);
    u_xlat2.xz = u_xlat1.xy;
    TGSM1[u_xlati31.x].value[(0 >> 2)] = floatBitsToUint(u_xlat2.x);
    TGSM1[u_xlati31.x].value[(0 >> 2) + 1] = floatBitsToUint(u_xlat2.y);
    TGSM1[u_xlati31.y].value[(0 >> 2)] = floatBitsToUint(u_xlat2.z);
    TGSM1[u_xlati31.y].value[(0 >> 2) + 1] = floatBitsToUint(u_xlat2.w);
    u_xlat2 = textureGather(sampler2D(LoResDB, samplerLoResDB), u_xlat15.xy);
    u_xlat2 = vec4(1.0, 1.0, 1.0, 1.0) / u_xlat2;
    u_xlat3 = textureGather(sampler2D(LoResDB, samplerLoResDB), u_xlat15.xy, 1);
    u_xlat3 = vec4(1.0, 1.0, 1.0, 1.0) / u_xlat3.zxwy;
    u_xlat4.xz = u_xlat2.wz;
    u_xlat4.yw = u_xlat3.zx;
    TGSM0[u_xlati0.x].value[(0 >> 2)] = floatBitsToUint(u_xlat4.x);
    TGSM0[u_xlati0.x].value[(0 >> 2) + 1] = floatBitsToUint(u_xlat4.y);
    TGSM0[u_xlati45].value[(0 >> 2)] = floatBitsToUint(u_xlat4.z);
    TGSM0[u_xlati45].value[(0 >> 2) + 1] = floatBitsToUint(u_xlat4.w);
    u_xlat3.xz = u_xlat2.xy;
    TGSM0[u_xlati31.x].value[(0 >> 2)] = floatBitsToUint(u_xlat3.x);
    TGSM0[u_xlati31.x].value[(0 >> 2) + 1] = floatBitsToUint(u_xlat3.y);
    TGSM0[u_xlati31.y].value[(0 >> 2)] = floatBitsToUint(u_xlat3.z);
    TGSM0[u_xlati31.y].value[(0 >> 2) + 1] = floatBitsToUint(u_xlat3.w);
    //memoryBarrierShared;
    barrier();
    u_xlatb0.xy = lessThan(uvec4(gl_LocalInvocationIndex, gl_LocalInvocationIndex, gl_LocalInvocationIndex, gl_LocalInvocationIndex), uvec4(39u, 45u, 0u, 0u)).xy;
    if(u_xlatb0.x){
        u_xlatu0 = gl_LocalInvocationIndex / 3u;
        u_xlatu1 = gl_LocalInvocationIndex % 3u;
        u_xlati30 = int(u_xlatu1) * 3;
        u_xlati0.x = int(u_xlatu0) * 16 + u_xlati30;
        u_xlat30.xy = vec2(uintBitsToFloat(TGSM1[u_xlati0.x].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM1[u_xlati0.x].value[(0 >> 2) + 1]));
        u_xlati1 = u_xlati0.xxxx + ivec4(1, 2, 3, 4);
        u_xlat2.xy = vec2(uintBitsToFloat(TGSM1[u_xlati1.x].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM1[u_xlati1.x].value[(0 >> 2) + 1]));
        u_xlat32.xy = vec2(uintBitsToFloat(TGSM1[u_xlati1.y].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM1[u_xlati1.y].value[(0 >> 2) + 1]));
        u_xlat3.xy = vec2(uintBitsToFloat(TGSM1[u_xlati1.z].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM1[u_xlati1.z].value[(0 >> 2) + 1]));
        u_xlat33.xy = vec2(uintBitsToFloat(TGSM1[u_xlati1.w].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM1[u_xlati1.w].value[(0 >> 2) + 1]));
        u_xlati4.xy = u_xlati0.xx + ivec2(5, 6);
        u_xlat34.xy = vec2(uintBitsToFloat(TGSM1[u_xlati4.x].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM1[u_xlati4.x].value[(0 >> 2) + 1]));
        u_xlat5.xy = vec2(uintBitsToFloat(TGSM1[u_xlati4.y].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM1[u_xlati4.y].value[(0 >> 2) + 1]));
        u_xlat35.xy = vec2(uintBitsToFloat(TGSM0[u_xlati0.x].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM0[u_xlati0.x].value[(0 >> 2) + 1]));
        u_xlat6.xy = vec2(uintBitsToFloat(TGSM0[u_xlati1.x].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM0[u_xlati1.x].value[(0 >> 2) + 1]));
        u_xlat36.xy = vec2(uintBitsToFloat(TGSM0[u_xlati1.y].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM0[u_xlati1.y].value[(0 >> 2) + 1]));
        u_xlat7.xy = vec2(uintBitsToFloat(TGSM0[u_xlati1.z].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM0[u_xlati1.z].value[(0 >> 2) + 1]));
        u_xlat31.xy = vec2(uintBitsToFloat(TGSM0[u_xlati1.w].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM0[u_xlati1.w].value[(0 >> 2) + 1]));
        u_xlat37.xy = vec2(uintBitsToFloat(TGSM0[u_xlati4.x].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM0[u_xlati4.x].value[(0 >> 2) + 1]));
        u_xlat4.xy = vec2(uintBitsToFloat(TGSM0[u_xlati4.y].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM0[u_xlati4.y].value[(0 >> 2) + 1]));
        u_xlat35.xy = (-u_xlat35.xy) + u_xlat6.xy;
        u_xlat6.xy = (-u_xlat6.xy) + u_xlat36.xy;
        u_xlat36.xy = (-u_xlat36.xy) + u_xlat7.xy;
        u_xlat7.xy = (-u_xlat7.xy) + u_xlat31.xy;
        u_xlat31.xy = (-u_xlat31.xy) + u_xlat37.xy;
        u_xlat4.xy = (-u_xlat37.xy) + u_xlat4.xy;
        u_xlat37.xy = u_xlat35.xy * u_xlat35.xy + AdditionalParams.yy;
        u_xlat8.xy = u_xlat6.xy * u_xlat6.xy + AdditionalParams.yy;
        u_xlat38.xy = u_xlat36.xy * u_xlat36.xy + AdditionalParams.yy;
        u_xlat9.xy = u_xlat7.xy * u_xlat7.xy + AdditionalParams.yy;
        u_xlat39.xy = u_xlat31.xy * u_xlat31.xy + AdditionalParams.yy;
        u_xlat10.xy = u_xlat4.xy * u_xlat4.xy + AdditionalParams.yy;
        u_xlat35.xy = u_xlat35.xy * u_xlat6.xy + AdditionalParams.yy;
        u_xlat35.xy = u_xlat35.xy * u_xlat35.xy;
        u_xlat37.xy = u_xlat37.xy * u_xlat8.xy;
        u_xlat37.xy = u_xlat37.xy * AdditionalParams.zz;
        u_xlat6.xy = u_xlat6.xy * u_xlat36.xy + AdditionalParams.yy;
        u_xlat8.xy = u_xlat38.xy * u_xlat8.xy;
        u_xlat6.zw = u_xlat36.xy * u_xlat7.xy + AdditionalParams.yy;
        u_xlat6 = u_xlat6 * u_xlat6;
        u_xlat8.zw = u_xlat38.xy * u_xlat9.xy;
        u_xlat8 = u_xlat8 * AdditionalParams.zzzz;
        u_xlat7.xy = u_xlat7.xy * u_xlat31.xy + AdditionalParams.yy;
        u_xlat7.xy = u_xlat7.xy * u_xlat7.xy;
        u_xlat9.xy = u_xlat39.xy * u_xlat9.xy;
        u_xlat9.xy = u_xlat9.xy * AdditionalParams.zz;
        u_xlat31.xy = u_xlat31.xy * u_xlat4.xy + AdditionalParams.yy;
        u_xlat31.xy = u_xlat31.xy * u_xlat31.xy;
        u_xlat4.xy = u_xlat39.xy * u_xlat10.xy;
        u_xlat4.xy = u_xlat4.xy * AdditionalParams.zz;
        u_xlatb35.xy = lessThan(u_xlat37.xyxy, u_xlat35.xyxy).xy;
        u_xlatb6 = lessThan(u_xlat8, u_xlat6);
        u_xlatb7.xy = lessThan(u_xlat9.xyxx, u_xlat7.xyxx).xy;
        u_xlatb31.xy = lessThan(u_xlat4.xyxy, u_xlat31.xyxy).xy;
        u_xlati4.xy = ivec2((uvec2(u_xlatb35.xy) * 0xffffffffu) | (uvec2(u_xlatb6.xy) * 0xffffffffu));
        u_xlati4.xy = ivec2(uvec2(u_xlati4.xy) & uvec2(1u, 1u));
        u_xlat4.x = (u_xlati4.x != 0) ? u_xlat2.x : u_xlat32.x;
        u_xlat4.y = (u_xlati4.y != 0) ? u_xlat2.y : u_xlat32.y;
        {
            vec2 hlslcc_movcTemp = u_xlat30;
            hlslcc_movcTemp.x = (u_xlatb35.x) ? u_xlat30.x : u_xlat4.x;
            hlslcc_movcTemp.y = (u_xlatb35.y) ? u_xlat30.y : u_xlat4.y;
            u_xlat30 = hlslcc_movcTemp;
        }
        u_xlati35.xy = ivec2((uvec2(u_xlatb6.xy) * 0xffffffffu) | (uvec2(u_xlatb6.zw) * 0xffffffffu));
        u_xlati35.xy = ivec2(uvec2(u_xlati35.xy) & uvec2(1u, 1u));
        u_xlat14.x = (u_xlati35.x != 0) ? u_xlat32.x : u_xlat3.x;
        u_xlat14.y = (u_xlati35.y != 0) ? u_xlat32.y : u_xlat3.y;
        u_xlat9.x = (u_xlati35.x != 0) ? u_xlat3.x : u_xlat32.x;
        u_xlat9.y = (u_xlati35.y != 0) ? u_xlat3.y : u_xlat32.y;
        u_xlat8.xy = u_xlat14.xy;
        u_xlat35.x = (u_xlatb6.z) ? u_xlat33.x : u_xlat9.x;
        u_xlat35.y = (u_xlatb6.w) ? u_xlat33.y : u_xlat9.y;
        u_xlat30.xy = u_xlat30.xy + u_xlat35.xy;
        u_xlat30.xy = u_xlat30.xy * vec2(0.5, 0.5) + u_xlat4.xy;
        u_xlat30.xy = u_xlat32.xy + u_xlat30.xy;
        u_xlat30.xy = u_xlat9.xy + u_xlat30.xy;
        u_xlat30.xy = u_xlat30.xy * vec2(0.25, 0.25);
        TGSM2[u_xlati0.x].value[(0 >> 2)] = floatBitsToUint(u_xlat30.x);
        TGSM2[u_xlati0.x].value[(0 >> 2) + 1] = floatBitsToUint(u_xlat30.y);
        u_xlat30.x = (u_xlatb6.x) ? u_xlat2.x : u_xlat8.x;
        u_xlat30.y = (u_xlatb6.y) ? u_xlat2.y : u_xlat8.y;
        u_xlati2.xy = ivec2((uvec2(u_xlatb6.zw) * 0xffffffffu) | (uvec2(u_xlatb7.xy) * 0xffffffffu));
        u_xlati2.xy = ivec2(uvec2(u_xlati2.xy) & uvec2(1u, 1u));
        u_xlat14.x = (u_xlati2.x != 0) ? u_xlat3.x : u_xlat33.x;
        u_xlat14.y = (u_xlati2.y != 0) ? u_xlat3.y : u_xlat33.y;
        u_xlat4.x = (u_xlati2.x != 0) ? u_xlat33.x : u_xlat3.x;
        u_xlat4.y = (u_xlati2.y != 0) ? u_xlat33.y : u_xlat3.y;
        u_xlat2.xy = u_xlat14.xy;
        u_xlat35.x = (u_xlatb7.x) ? u_xlat34.x : u_xlat4.x;
        u_xlat35.y = (u_xlatb7.y) ? u_xlat34.y : u_xlat4.y;
        u_xlat30.xy = u_xlat30.xy + u_xlat35.xy;
        u_xlat30.xy = u_xlat30.xy * vec2(0.5, 0.5) + u_xlat8.xy;
        u_xlat30.xy = u_xlat3.xy + u_xlat30.xy;
        u_xlat30.xy = u_xlat4.xy + u_xlat30.xy;
        u_xlat30.xy = u_xlat30.xy * vec2(0.25, 0.25);
        TGSM2[u_xlati1.x].value[(0 >> 2)] = floatBitsToUint(u_xlat30.x);
        TGSM2[u_xlati1.x].value[(0 >> 2) + 1] = floatBitsToUint(u_xlat30.y);
        u_xlat30.x = (u_xlatb6.z) ? u_xlat32.x : u_xlat2.x;
        u_xlat30.y = (u_xlatb6.w) ? u_xlat32.y : u_xlat2.y;
        u_xlati32.xy = ivec2((uvec2(u_xlatb7.xy) * 0xffffffffu) | (uvec2(u_xlatb31.xy) * 0xffffffffu));
        u_xlati32.xy = ivec2(uvec2(u_xlati32.xy) & uvec2(1u, 1u));
        u_xlat32.x = (u_xlati32.x != 0) ? u_xlat34.x : u_xlat33.x;
        u_xlat32.y = (u_xlati32.y != 0) ? u_xlat34.y : u_xlat33.y;
        u_xlat1.x = (u_xlatb31.x) ? u_xlat5.x : u_xlat32.x;
        u_xlat1.z = (u_xlatb31.y) ? u_xlat5.y : u_xlat32.y;
        u_xlat30.xy = u_xlat30.xy + u_xlat1.xz;
        u_xlat30.xy = u_xlat30.xy * vec2(0.5, 0.5) + u_xlat2.xy;
        u_xlat30.xy = u_xlat33.xy + u_xlat30.xy;
        u_xlat30.xy = u_xlat32.xy + u_xlat30.xy;
        u_xlat30.xy = u_xlat30.xy * vec2(0.25, 0.25);
        TGSM2[u_xlati1.y].value[(0 >> 2)] = floatBitsToUint(u_xlat30.x);
        TGSM2[u_xlati1.y].value[(0 >> 2) + 1] = floatBitsToUint(u_xlat30.y);
    }
    //memoryBarrierShared;
    barrier();
    if(u_xlatb0.y){
        u_xlatu0 = gl_LocalInvocationIndex / 9u;
        u_xlatu1 = gl_LocalInvocationIndex % 9u;
        u_xlati0.x = int(u_xlatu0) * 32 + int(u_xlatu1);
        u_xlat15.xy = vec2(uintBitsToFloat(TGSM2[u_xlati0.x].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM2[u_xlati0.x].value[(0 >> 2) + 1]));
        u_xlati45 = u_xlati0.x + 16;
        u_xlat1.xy = vec2(uintBitsToFloat(TGSM2[u_xlati45].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM2[u_xlati45].value[(0 >> 2) + 1]));
        u_xlati2 = u_xlati0.xxxx + ivec4(32, 48, 64, 80);
        u_xlat31.xy = vec2(uintBitsToFloat(TGSM2[u_xlati2.x].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM2[u_xlati2.x].value[(0 >> 2) + 1]));
        u_xlat2.xy = vec2(uintBitsToFloat(TGSM2[u_xlati2.y].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM2[u_xlati2.y].value[(0 >> 2) + 1]));
        u_xlat3.xy = vec2(uintBitsToFloat(TGSM2[u_xlati2.z].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM2[u_xlati2.z].value[(0 >> 2) + 1]));
        u_xlat32.xy = vec2(uintBitsToFloat(TGSM2[u_xlati2.w].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM2[u_xlati2.w].value[(0 >> 2) + 1]));
        u_xlati4 = u_xlati0.xxxx + ivec4(2, 18, 34, 50);
        u_xlat33.xy = vec2(uintBitsToFloat(TGSM0[u_xlati4.x].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM0[u_xlati4.x].value[(0 >> 2) + 1]));
        u_xlat4.xy = vec2(uintBitsToFloat(TGSM0[u_xlati4.y].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM0[u_xlati4.y].value[(0 >> 2) + 1]));
        u_xlat5.xy = vec2(uintBitsToFloat(TGSM0[u_xlati4.z].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM0[u_xlati4.z].value[(0 >> 2) + 1]));
        u_xlat34.xy = vec2(uintBitsToFloat(TGSM0[u_xlati4.w].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM0[u_xlati4.w].value[(0 >> 2) + 1]));
        u_xlati35.xy = u_xlati0.xx + ivec2(66, 82);
        u_xlat6.xy = vec2(uintBitsToFloat(TGSM0[u_xlati35.x].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM0[u_xlati35.x].value[(0 >> 2) + 1]));
        u_xlat35.xy = vec2(uintBitsToFloat(TGSM0[u_xlati35.y].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM0[u_xlati35.y].value[(0 >> 2) + 1]));
        u_xlat33.xy = (-u_xlat33.xy) + u_xlat4.xy;
        u_xlat4.xy = (-u_xlat4.xy) + u_xlat5.xy;
        u_xlat5.xy = (-u_xlat5.xy) + u_xlat34.xy;
        u_xlat34.xy = (-u_xlat34.xy) + u_xlat6.xy;
        u_xlat35.xy = (-u_xlat6.xy) + u_xlat35.xy;
        u_xlat6.xy = u_xlat33.xy * u_xlat33.xy + AdditionalParams.yy;
        u_xlat36.xy = u_xlat4.xy * u_xlat4.xy + AdditionalParams.yy;
        u_xlat7.xy = u_xlat5.xy * u_xlat5.xy + AdditionalParams.yy;
        u_xlat37.xy = u_xlat34.xy * u_xlat34.xy + AdditionalParams.yy;
        u_xlat8.xy = u_xlat35.xy * u_xlat35.xy + AdditionalParams.yy;
        u_xlat33.xy = u_xlat33.xy * u_xlat4.xy + AdditionalParams.yy;
        u_xlat33.xy = u_xlat33.xy * u_xlat33.xy;
        u_xlat6.xy = u_xlat36.xy * u_xlat6.xy;
        u_xlat4.xy = u_xlat4.xy * u_xlat5.xy + AdditionalParams.yy;
        u_xlat6.zw = u_xlat36.xy * u_xlat7.xy;
        u_xlat6 = u_xlat6 * AdditionalParams.zzzz;
        u_xlat5.xy = u_xlat5.xy * u_xlat34.xy + AdditionalParams.yy;
        u_xlat5.xy = u_xlat5.xy * u_xlat5.xy;
        u_xlat7.xy = u_xlat37.xy * u_xlat7.xy;
        u_xlat7.xy = u_xlat7.xy * AdditionalParams.zz;
        u_xlat4.zw = u_xlat34.xy * u_xlat35.xy + AdditionalParams.yy;
        u_xlat4 = u_xlat4 * u_xlat4;
        u_xlat35.xy = u_xlat37.xy * u_xlat8.xy;
        u_xlat35.xy = u_xlat35.xy * AdditionalParams.zz;
        u_xlatb33.xy = lessThan(u_xlat6.xyxy, u_xlat33.xyxy).xy;
        u_xlatb4.xy = lessThan(u_xlat6.zwzz, u_xlat4.xyxx).xy;
        u_xlatb5.xy = lessThan(u_xlat7.xyxx, u_xlat5.xyxx).xy;
        u_xlatb34.xy = lessThan(u_xlat35.xyxy, u_xlat4.zwzw).xy;
        u_xlati35.xy = ivec2((uvec2(u_xlatb33.xy) * 0xffffffffu) | (uvec2(u_xlatb4.xy) * 0xffffffffu));
        u_xlati35.xy = ivec2(uvec2(u_xlati35.xy) & uvec2(1u, 1u));
        u_xlat35.x = (u_xlati35.x != 0) ? u_xlat1.x : u_xlat31.x;
        u_xlat35.y = (u_xlati35.y != 0) ? u_xlat1.y : u_xlat31.y;
        {
            vec2 hlslcc_movcTemp = u_xlat15;
            hlslcc_movcTemp.x = (u_xlatb33.x) ? u_xlat15.x : u_xlat35.x;
            hlslcc_movcTemp.y = (u_xlatb33.y) ? u_xlat15.y : u_xlat35.y;
            u_xlat15 = hlslcc_movcTemp;
        }
        u_xlati33.xy = ivec2((uvec2(u_xlatb4.xy) * 0xffffffffu) | (uvec2(u_xlatb5.xy) * 0xffffffffu));
        u_xlati33.xy = ivec2(uvec2(u_xlati33.xy) & uvec2(1u, 1u));
        u_xlat14.x = (u_xlati33.x != 0) ? u_xlat31.x : u_xlat2.x;
        u_xlat14.y = (u_xlati33.y != 0) ? u_xlat31.y : u_xlat2.y;
        u_xlat7.x = (u_xlati33.x != 0) ? u_xlat2.x : u_xlat31.x;
        u_xlat7.y = (u_xlati33.y != 0) ? u_xlat2.y : u_xlat31.y;
        u_xlat6.xy = u_xlat14.xy;
        u_xlat33.x = (u_xlatb5.x) ? u_xlat3.x : u_xlat7.x;
        u_xlat33.y = (u_xlatb5.y) ? u_xlat3.y : u_xlat7.y;
        u_xlat15.xy = u_xlat15.xy + u_xlat33.xy;
        u_xlat15.xy = u_xlat15.xy * vec2(0.5, 0.5) + u_xlat35.xy;
        u_xlat15.xy = u_xlat31.xy + u_xlat15.xy;
        u_xlat15.xy = u_xlat7.xy + u_xlat15.xy;
        u_xlat15.xy = u_xlat15.xy * vec2(0.25, 0.25);
        {
            vec4 hlslcc_movcTemp = u_xlat1;
            hlslcc_movcTemp.x = (u_xlatb4.x) ? u_xlat1.x : u_xlat6.x;
            hlslcc_movcTemp.y = (u_xlatb4.y) ? u_xlat1.y : u_xlat6.y;
            u_xlat1 = hlslcc_movcTemp;
        }
        u_xlati31.xy = ivec2((uvec2(u_xlatb5.xy) * 0xffffffffu) | (uvec2(u_xlatb34.xy) * 0xffffffffu));
        u_xlati31.xy = ivec2(uvec2(u_xlati31.xy) & uvec2(1u, 1u));
        u_xlat31.x = (u_xlati31.x != 0) ? u_xlat3.x : u_xlat2.x;
        u_xlat31.y = (u_xlati31.y != 0) ? u_xlat3.y : u_xlat2.y;
        {
            vec2 hlslcc_movcTemp = u_xlat32;
            hlslcc_movcTemp.x = (u_xlatb34.x) ? u_xlat32.x : u_xlat31.x;
            hlslcc_movcTemp.y = (u_xlatb34.y) ? u_xlat32.y : u_xlat31.y;
            u_xlat32 = hlslcc_movcTemp;
        }
        u_xlat1.xy = u_xlat1.xy + u_xlat32.xy;
        u_xlat1.xy = u_xlat1.xy * vec2(0.5, 0.5) + u_xlat6.xy;
        u_xlat1.xy = u_xlat2.xy + u_xlat1.xy;
        u_xlat1.xy = u_xlat31.xy + u_xlat1.xy;
        u_xlat1.xy = u_xlat1.xy * vec2(0.25, 0.25);
        TGSM1[u_xlati0.x].value[(0 >> 2)] = floatBitsToUint(u_xlat15.x);
        TGSM1[u_xlati0.x].value[(0 >> 2) + 1] = floatBitsToUint(u_xlat15.y);
        TGSM1[u_xlati45].value[(0 >> 2)] = floatBitsToUint(u_xlat1.x);
        TGSM1[u_xlati45].value[(0 >> 2) + 1] = floatBitsToUint(u_xlat1.y);
    }
    //memoryBarrierShared;
    barrier();
    u_xlati0.x = int(gl_LocalInvocationID.y) * 16 + int(gl_LocalInvocationID.x);
    u_xlati15.xyz = u_xlati0.xxx + ivec3(16, 17, 1);
    u_xlat1.xy = vec2(uintBitsToFloat(TGSM1[u_xlati15.x].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM1[u_xlati15.x].value[(0 >> 2) + 1]));
    u_xlat15.xy = vec2(uintBitsToFloat(TGSM1[u_xlati15.y].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM1[u_xlati15.y].value[(0 >> 2) + 1]));
    u_xlat1.zw = vec2(uintBitsToFloat(TGSM1[u_xlati15.z].value[(0 >> 2) + 0]), uintBitsToFloat(TGSM1[u_xlati15.z].value[(0 >> 2) + 1]));
    u_xlat2.xy = vec2(uintBitsToFloat(TGSM1[u_xlati0.x].value[(0 >> 2) + 1]), uintBitsToFloat(TGSM1[u_xlati0.x].value[(0 >> 2) + 0]));
    u_xlat0.xw = vec2(gl_GlobalInvocationID.xy);
    u_xlat0.xw = u_xlat0.xw * InvLowResolution.xy;
    u_xlatu3 = gl_GlobalInvocationID.xyyy << uvec4(1u, 1u, 1u, 1u);
    u_xlat4.xy = vec2(u_xlatu3.xw);
    u_xlat4.xy = u_xlat4.xy * InvHighResolution.xy;
    u_xlat5 = textureGather(sampler2D(HiResAO, samplerHiResAO), u_xlat4.xy);
    u_xlat6 = textureGather(sampler2D(HiResAO, samplerHiResAO), u_xlat4.xy, 1);
    u_xlat7 = textureGather(sampler2D(LoResDB, samplerLoResDB), u_xlat0.xw);
    u_xlat8 = textureGather(sampler2D(LoResDB, samplerLoResDB), u_xlat0.xw, 1);
    u_xlat9 = textureGather(sampler2D(HiResDB, samplerHiResDB), u_xlat4.xy);
    u_xlat4 = textureGather(sampler2D(HiResDB, samplerHiResDB), u_xlat4.xy, 1);
    u_xlati10 = ivec4(u_xlatu3.xwxw) + ivec4(int(0xFFFFFFFFu), 0, 0, int(0xFFFFFFFFu));
    u_xlat11 = (-u_xlat7) + u_xlat9.xxxx;
    u_xlat11 = abs(u_xlat11) + AdditionalParams.wwww;
    u_xlat11 = vec4(9.0, 3.0, 1.0, 3.0) / u_xlat11;
    u_xlat0.x = dot(u_xlat11, vec4(1.0, 1.0, 1.0, 1.0));
    u_xlat12.z = u_xlat15.x;
    u_xlat12.yw = u_xlat1.xz;
    u_xlat12.x = u_xlat2.y;
    u_xlat0.y = dot(u_xlat12.yzwx, u_xlat11);
    u_xlat0.xy = u_xlat0.xy + AdditionalParams.xx;
    u_xlat15.x = u_xlat0.y * u_xlat5.x;
    u_xlat11.xzw = u_xlat15.xxx / u_xlat0.xxx;
    u_xlat13 = (-u_xlat8) + u_xlat4.xxxx;
    u_xlat13 = abs(u_xlat13) + AdditionalParams.wwww;
    u_xlat13 = vec4(9.0, 3.0, 1.0, 3.0) / u_xlat13;
    u_xlat0.x = dot(u_xlat13, vec4(1.0, 1.0, 1.0, 1.0));
    u_xlat2.z = u_xlat15.y;
    u_xlat2.yw = u_xlat1.yw;
    u_xlat0.y = dot(u_xlat2.yzwx, u_xlat13);
    u_xlat0.xy = u_xlat0.xy + AdditionalParams.xx;
    u_xlat15.x = u_xlat0.y * u_xlat6.x;
    u_xlat11.y = u_xlat15.x / u_xlat0.x;
    imageStore(AoResult_origX0X, u_xlati10.xy, u_xlat11);
    u_xlat0 = (-u_xlat7.yzwx) + u_xlat9.yyyy;
    u_xlat0 = abs(u_xlat0) + AdditionalParams.wwww;
    u_xlat0 = vec4(9.0, 3.0, 1.0, 3.0) / u_xlat0;
    u_xlat1.x = dot(u_xlat0, vec4(1.0, 1.0, 1.0, 1.0));
    u_xlat1.x = u_xlat1.x + AdditionalParams.x;
    u_xlat0.x = dot(u_xlat12.zwxy, u_xlat0);
    u_xlat0.x = u_xlat0.x + AdditionalParams.x;
    u_xlat0.x = u_xlat0.x * u_xlat5.y;
    u_xlat0.xzw = u_xlat0.xxx / u_xlat1.xxx;
    u_xlat1 = (-u_xlat8.yzwx) + u_xlat4.yyyy;
    u_xlat1 = abs(u_xlat1) + AdditionalParams.wwww;
    u_xlat1 = vec4(9.0, 3.0, 1.0, 3.0) / u_xlat1;
    u_xlat4.x = dot(u_xlat1, vec4(1.0, 1.0, 1.0, 1.0));
    u_xlat4.x = u_xlat4.x + AdditionalParams.x;
    u_xlat1.x = dot(u_xlat2.zwxy, u_xlat1);
    u_xlat1.x = u_xlat1.x + AdditionalParams.x;
    u_xlat1.x = u_xlat1.x * u_xlat6.y;
    u_xlat0.y = u_xlat1.x / u_xlat4.x;
    imageStore(AoResult_origX0X, ivec2(u_xlatu3.xw), u_xlat0);
    u_xlat0 = (-u_xlat7.zwxy) + u_xlat9.zzzz;
    u_xlat0 = abs(u_xlat0) + AdditionalParams.wwww;
    u_xlat0 = vec4(9.0, 3.0, 1.0, 3.0) / u_xlat0;
    u_xlat1.x = dot(u_xlat0, vec4(1.0, 1.0, 1.0, 1.0));
    u_xlat1.x = u_xlat1.x + AdditionalParams.x;
    u_xlat0.x = dot(u_xlat12.wxyz, u_xlat0);
    u_xlat0.x = u_xlat0.x + AdditionalParams.x;
    u_xlat0.x = u_xlat0.x * u_xlat5.z;
    u_xlat0.xzw = u_xlat0.xxx / u_xlat1.xxx;
    u_xlat1 = (-u_xlat8.zwxy) + u_xlat4.zzzz;
    u_xlat1 = abs(u_xlat1) + AdditionalParams.wwww;
    u_xlat1 = vec4(9.0, 3.0, 1.0, 3.0) / u_xlat1;
    u_xlat4.x = dot(u_xlat1, vec4(1.0, 1.0, 1.0, 1.0));
    u_xlat4.x = u_xlat4.x + AdditionalParams.x;
    u_xlat1.x = dot(u_xlat2.wxyz, u_xlat1);
    u_xlat1.x = u_xlat1.x + AdditionalParams.x;
    u_xlat1.x = u_xlat1.x * u_xlat6.z;
    u_xlat0.y = u_xlat1.x / u_xlat4.x;
    imageStore(AoResult_origX0X, u_xlati10.zw, u_xlat0);
    u_xlati0 = ivec4(u_xlatu3) + ivec4(int(0xFFFFFFFFu), int(0xFFFFFFFFu), int(0xFFFFFFFFu), int(0xFFFFFFFFu));
    u_xlat1 = (-u_xlat7.wxyz) + u_xlat9.wwww;
    u_xlat1 = abs(u_xlat1) + AdditionalParams.wwww;
    u_xlat1 = vec4(9.0, 3.0, 1.0, 3.0) / u_xlat1;
    u_xlat3.x = dot(u_xlat1, vec4(1.0, 1.0, 1.0, 1.0));
    u_xlat3.x = u_xlat3.x + AdditionalParams.x;
    u_xlat1.x = dot(u_xlat12, u_xlat1);
    u_xlat1.x = u_xlat1.x + AdditionalParams.x;
    u_xlat1.x = u_xlat1.x * u_xlat5.w;
    u_xlat1.xzw = u_xlat1.xxx / u_xlat3.xxx;
    u_xlat3 = (-u_xlat8.wxyz) + u_xlat4.wwww;
    u_xlat3 = abs(u_xlat3) + AdditionalParams.wwww;
    u_xlat3 = vec4(9.0, 3.0, 1.0, 3.0) / u_xlat3;
    u_xlat4.x = dot(u_xlat3, vec4(1.0, 1.0, 1.0, 1.0));
    u_xlat4.x = u_xlat4.x + AdditionalParams.x;
    u_xlat2.x = dot(u_xlat2, u_xlat3);
    u_xlat2.x = u_xlat2.x + AdditionalParams.x;
    u_xlat2.x = u_xlat2.x * u_xlat6.w;
    u_xlat1.y = u_xlat2.x / u_xlat4.x;
    imageStore(AoResult_origX0X, u_xlati0.xy, u_xlat1);
    return;
}

