#version 440
#extension GL_ARB_explicit_attrib_location : require
#extension GL_ARB_shading_language_420pack : require

layout(origin_upper_left) in vec4 gl_FragCoord;
#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
#if HLSLCC_ENABLE_UNIFORM_BUFFERS
#define UNITY_UNIFORM
#else
#define UNITY_UNIFORM uniform
#endif
#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
#if UNITY_SUPPORTS_UNIFORM_LOCATION
#define UNITY_LOCATION(x) layout(location = x)
#define UNITY_BINDING(x) layout(binding = x, std140)
#else
#define UNITY_LOCATION(x)
#define UNITY_BINDING(x) layout(std140)
#endif
precise vec4 u_xlat_precise_vec4;
precise ivec4 u_xlat_precise_ivec4;
precise bvec4 u_xlat_precise_bvec4;
precise uvec4 u_xlat_precise_uvec4;
const uvec4 ImmCB_0[] = uvec4[4] (
	uvec4(0x3F800000, 0x0, 0x0, 0x0),
	uvec4(0x0, 0x3F800000, 0x0, 0x0),
	uvec4(0x0, 0x0, 0x3F800000, 0x0),
	uvec4(0x0, 0x0, 0x0, 0x3F800000));
layout(set = 1, binding = 0, std140) uniform PGlobals {
	vec2 _GlobalMipBias;
	vec4 _MainLightPosition;
	vec4 _MainLightColor;
	vec4 _AdditionalLightsCount;
	vec3 _WorldSpaceCameraPos;
	vec4 _ProjectionParams;
	vec4 unity_FogParams;
	vec4 unity_FogColor;
	mat4x4 unity_MatrixV;
};
layout(set = 1, binding = 1, std140) uniform AdditionalLights {
	vec4 _AdditionalLightsPosition[32];
	vec4 _AdditionalLightsColor[32];
	vec4 _AdditionalLightsAttenuation[32];
	vec4 _AdditionalLightsSpotDir[32];
	vec4 _AdditionalLightsOcclusionProbes[32];
	float _AdditionalLightsLayerMasks[32];
};
layout(set = 1, binding = 2, std140) uniform UnityPerDraw {
	mat4x4 unity_ObjectToWorld;
	mat4x4 unity_WorldToObject;
	vec4 unity_LODFade;
	vec4 unity_WorldTransformParams;
	vec4 unity_RenderingLayer;
	vec4 unity_LightData;
	vec4 unity_LightIndices[2];
	vec4 unity_ProbesOcclusion;
	vec4 unity_SpecCube0_HDR;
	vec4 unity_SpecCube1_HDR;
	vec4 unity_SpecCube0_BoxMax;
	vec4 unity_SpecCube0_BoxMin;
	vec4 unity_SpecCube0_ProbePosition;
	vec4 unity_SpecCube1_BoxMax;
	vec4 unity_SpecCube1_BoxMin;
	vec4 unity_SpecCube1_ProbePosition;
	vec4 unity_LightmapST;
	vec4 unity_DynamicLightmapST;
	vec4 unity_SHAr;
	vec4 unity_SHAg;
	vec4 unity_SHAb;
	vec4 unity_SHBr;
	vec4 unity_SHBg;
	vec4 unity_SHBb;
	vec4 unity_SHC;
	vec4 unity_RendererBounds_Min;
	vec4 unity_RendererBounds_Max;
	mat4x4 unity_MatrixPreviousM;
	mat4x4 unity_MatrixPreviousMI;
	vec4 unity_MotionVectorsParams;
	vec4 unity_SpriteColor;
	vec4 unity_SpriteProps;
};
layout(set = 1, binding = 3, std140) uniform _Terrain {
	float _NormalScale0;
	float _NormalScale1;
	float _NormalScale2;
	float _NormalScale3;
	float _Metallic0;
	float _Metallic1;
	float _Metallic2;
	float _Metallic3;
	float _Smoothness0;
	float _Smoothness1;
	float _Smoothness2;
	float _Smoothness3;
	vec4 _DiffuseRemapScale0;
	vec4 _DiffuseRemapScale1;
	vec4 _DiffuseRemapScale2;
	vec4 _DiffuseRemapScale3;
	vec4 _MaskMapRemapOffset0;
	vec4 _MaskMapRemapOffset1;
	vec4 _MaskMapRemapOffset2;
	vec4 _MaskMapRemapOffset3;
	vec4 _MaskMapRemapScale0;
	vec4 _MaskMapRemapScale1;
	vec4 _MaskMapRemapScale2;
	vec4 _MaskMapRemapScale3;
	vec4 _Control_ST;
	vec4 _Control_TexelSize;
	float _DiffuseHasAlpha0;
	float _DiffuseHasAlpha1;
	float _DiffuseHasAlpha2;
	float _DiffuseHasAlpha3;
	float _LayerHasMask0;
	float _LayerHasMask1;
	float _LayerHasMask2;
	float _LayerHasMask3;
	vec4 _Splat0_ST;
	vec4 _Splat1_ST;
	vec4 _Splat2_ST;
	vec4 _Splat3_ST;
	float _HeightTransition;
	float _NumLayersCount;
	vec4 _TerrainHeightmapRecipSize;
	vec4 _TerrainHeightmapScale;
};
layout(set = 1, binding = 4, std140) uniform LightShadows {
	mat4x4 _MainLightWorldToShadow[5];
	vec4 _CascadeShadowSplitSpheres0;
	vec4 _CascadeShadowSplitSpheres1;
	vec4 _CascadeShadowSplitSpheres2;
	vec4 _CascadeShadowSplitSpheres3;
	vec4 _CascadeShadowSplitSphereRadii;
	vec4 _MainLightShadowOffset0;
	vec4 _MainLightShadowOffset1;
	vec4 _MainLightShadowParams;
	vec4 _MainLightShadowmapSize;
	vec4 _AdditionalShadowOffset0;
	vec4 _AdditionalShadowOffset1;
	vec4 _AdditionalShadowFadeParams;
	vec4 _AdditionalShadowmapSize;
	vec4 _AdditionalShadowParams[32];
	mat4x4 _AdditionalLightsWorldToShadow[32];
};
layout(set = 1, binding = 5, std140) uniform LightCookies {
	mat4x4 _MainLightWorldToLight;
	float _AdditionalLightsCookieEnableBits;
	float _MainLightCookieTextureFormat;
	float _AdditionalLightsCookieAtlasTextureFormat;
	mat4x4 _AdditionalLightsWorldToLights[32];
	vec4 _AdditionalLightsCookieAtlasUVRects[32];
	float _AdditionalLightsLightTypes[32];
};
layout(set = 0, binding = 0) uniform mediump textureCube unity_SpecCube0;
layout(set = 0, binding = 1) uniform mediump texture2D unity_Lightmap;
layout(set = 0, binding = 2) uniform mediump texture2D unity_LightmapInd;
layout(set = 0, binding = 3) uniform mediump texture2D _Control;
layout(set = 0, binding = 4) uniform mediump texture2D _Splat0;
layout(set = 0, binding = 5) uniform mediump texture2D _Splat1;
layout(set = 0, binding = 6) uniform mediump texture2D _Splat2;
layout(set = 0, binding = 7) uniform mediump texture2D _Splat3;
layout(set = 0, binding = 8) uniform mediump texture2D _Normal0;
layout(set = 0, binding = 9) uniform mediump texture2D _Normal1;
layout(set = 0, binding = 10) uniform mediump texture2D _Normal2;
layout(set = 0, binding = 11) uniform mediump texture2D _Normal3;
layout(set = 0, binding = 12) uniform mediump texture2D _MainLightShadowmapTexture;
layout(set = 0, binding = 13) uniform mediump texture2D _AdditionalLightsShadowmapTexture;
layout(set = 0, binding = 14) uniform mediump texture2D _MainLightCookieTexture;
layout(set = 0, binding = 15) uniform mediump texture2D _AdditionalLightsCookieAtlasTexture;
layout(location = 0) in highp  vec4 vs_TEXCOORD0;
layout(location = 1) in highp  vec4 vs_TEXCOORD1;
layout(location = 2) in highp  vec4 vs_TEXCOORD2;
layout(location = 3) in highp  vec4 vs_TEXCOORD3;
layout(location = 4) in highp  vec4 vs_TEXCOORD4;
layout(location = 5) in highp  vec4 vs_TEXCOORD5;
layout(location = 6) in highp  vec3 vs_TEXCOORD7;
layout(location = 7) in highp  vec4 vs_TEXCOORD8;
layout(location = 0) out highp vec4 SV_Target0;
vec3 u_xlat0;
vec4 u_xlat1;
vec4 u_xlat2;
vec4 u_xlat3;
vec4 u_xlat4;
vec4 u_xlat5;
bool u_xlatb5;
vec4 u_xlat6;
bvec2 u_xlatb6;
vec4 u_xlat7;
vec4 u_xlat8;
vec4 u_xlat9;
vec4 u_xlat10;
vec4 u_xlat11;
int u_xlati11;
bvec4 u_xlatb11;
vec4 u_xlat12;
vec4 u_xlat13;
vec4 u_xlat14;
vec4 u_xlat15;
vec4 u_xlat16;
vec4 u_xlat17;
vec4 u_xlat18;
vec4 u_xlat19;
vec4 u_xlat20;
vec4 u_xlat21;
vec4 u_xlat22;
vec4 u_xlat23;
vec4 u_xlat24;
vec4 u_xlat25;
float u_xlat26;
vec3 u_xlat29;
vec3 u_xlat31;
uint u_xlatu31;
bool u_xlatb31;
vec2 u_xlat33;
vec3 u_xlat37;
vec3 u_xlat39;
vec2 u_xlat40;
float u_xlat52;
uint u_xlatu52;
vec2 u_xlat57;
bvec2 u_xlatb57;
vec2 u_xlat58;
int u_xlati58;
uint u_xlatu58;
bool u_xlatb58;
vec2 u_xlat60;
vec2 u_xlat61;
vec2 u_xlat64;
vec2 u_xlat66;
vec2 u_xlat67;
vec2 u_xlat72;
float u_xlat78;
float u_xlat79;
bool u_xlatb79;
float u_xlat80;
float u_xlat82;
float u_xlat83;
float u_xlat84;
int u_xlati84;
float u_xlat85;
float u_xlat86;
int u_xlati86;
bool u_xlatb86;
float u_xlat87;
int u_xlati87;
bool u_xlatb87;
float u_xlat88;
int u_xlati88;
bool u_xlatb88;
float u_xlat89;
layout(set = 0, binding = 16) uniform mediump  sampler samplerunity_SpecCube0;
layout(set = 0, binding = 17) uniform mediump  sampler samplerunity_Lightmap;
layout(set = 0, binding = 18) uniform mediump  sampler sampler_Control;
layout(set = 0, binding = 19) uniform mediump  sampler sampler_Splat0;
layout(set = 0, binding = 20) uniform mediump  sampler sampler_Normal0;
layout(set = 0, binding = 21) uniform mediump  sampler sampler_LinearClamp;
layout(set = 0, binding = 22) uniform mediump  samplerShadow sampler_LinearClampCompare;
layout(set = 0, binding = 23) uniform mediump  sampler sampler_MainLightCookieTexture;
void main()
{
    u_xlat0.xyz = _MaskMapRemapScale0.xyw * vec3(0.5, 0.5, 0.5) + _MaskMapRemapOffset0.xyw;
    u_xlat1.xyz = _MaskMapRemapScale1.xyw * vec3(0.5, 0.5, 0.5) + _MaskMapRemapOffset1.xyw;
    u_xlat2.xyz = _MaskMapRemapScale2.xyw * vec3(0.5, 0.5, 0.5) + _MaskMapRemapOffset2.xyw;
    u_xlat3.xyw = _MaskMapRemapScale3.xwy * vec3(0.5, 0.5, 0.5) + _MaskMapRemapOffset3.xwy;
    u_xlat4.xy = _Control_TexelSize.zw + vec2(-1.0, -1.0);
    u_xlat4.xy = vs_TEXCOORD0.xy * u_xlat4.xy + vec2(0.5, 0.5);
    u_xlat4.xy = u_xlat4.xy * _Control_TexelSize.xy;
    u_xlat4 = texture(sampler2D(_Control, sampler_Control), u_xlat4.xy, _GlobalMipBias.x);
    u_xlat78 = dot(u_xlat4, vec4(1.0, 1.0, 1.0, 1.0));
    u_xlat5 = texture(sampler2D(_Splat0, sampler_Splat0), vs_TEXCOORD1.xy, _GlobalMipBias.x);
    u_xlat6 = texture(sampler2D(_Splat1, sampler_Splat0), vs_TEXCOORD1.zw, _GlobalMipBias.x);
    u_xlat7 = texture(sampler2D(_Splat2, sampler_Splat0), vs_TEXCOORD2.xy, _GlobalMipBias.x);
    u_xlat8 = texture(sampler2D(_Splat3, sampler_Splat0), vs_TEXCOORD2.zw, _GlobalMipBias.x);
    u_xlat9.x = u_xlat5.w;
    u_xlat9.y = u_xlat6.w;
    u_xlat9.z = u_xlat7.w;
    u_xlat9.w = u_xlat8.w;
    u_xlat10 = u_xlat9 * vec4(_Smoothness0, _Smoothness1, _Smoothness2, _Smoothness3);
    u_xlatb79 = 4.0>=_NumLayersCount;
    u_xlat11 = (-u_xlat4) + vec4(1.0, 1.0, 1.0, 1.0);
    u_xlat11 = u_xlat9 + (-u_xlat11);
    u_xlat11 = u_xlat11 * vec4(20.0, 20.0, 20.0, 20.0);
    u_xlat11 = clamp(u_xlat11, 0.0, 1.0);
    u_xlat11 = u_xlat4 * vec4(0.00100000005, 0.00100000005, 0.00100000005, 0.00100000005) + u_xlat11;
    u_xlat12 = u_xlat4 + (-u_xlat11);
    u_xlat13.x = u_xlat12.x * _DiffuseRemapScale0.w;
    u_xlat13.y = u_xlat12.y * _DiffuseRemapScale1.w;
    u_xlat13.z = u_xlat12.z * _DiffuseRemapScale2.w;
    u_xlat13.w = u_xlat12.w * _DiffuseRemapScale3.w;
    u_xlat11 = u_xlat11 + u_xlat13;
    u_xlat4 = (bool(u_xlatb79)) ? u_xlat11 : u_xlat4;
    u_xlat79 = dot(u_xlat4, vec4(1.0, 1.0, 1.0, 1.0));
    u_xlat79 = u_xlat79 + 6.10351562e-05;
    u_xlat4 = u_xlat4 / vec4(u_xlat79);
    u_xlat11.xyz = u_xlat4.xxx * _DiffuseRemapScale0.xyz;
    u_xlat12.xyz = u_xlat4.yyy * _DiffuseRemapScale1.xyz;
    u_xlat6.xyz = u_xlat6.xyz * u_xlat12.xyz;
    u_xlat5.xyz = u_xlat5.xyz * u_xlat11.xyz + u_xlat6.xyz;
    u_xlat6.xyz = u_xlat4.zzz * _DiffuseRemapScale2.xyz;
    u_xlat5.xyz = u_xlat7.xyz * u_xlat6.xyz + u_xlat5.xyz;
    u_xlat6.xyz = u_xlat4.www * _DiffuseRemapScale3.xyz;
    u_xlat5.xyz = u_xlat8.xyz * u_xlat6.xyz + u_xlat5.xyz;
    u_xlat6.xyz = texture(sampler2D(_Normal0, sampler_Normal0), vs_TEXCOORD1.xy, _GlobalMipBias.x).xyw;
    u_xlat6.x = u_xlat6.x * u_xlat6.z;
    u_xlat6.xy = u_xlat6.xy * vec2(2.0, 2.0) + vec2(-1.0, -1.0);
    u_xlat79 = dot(u_xlat6.xy, u_xlat6.xy);
    u_xlat79 = min(u_xlat79, 1.0);
    u_xlat79 = (-u_xlat79) + 1.0;
    u_xlat79 = sqrt(u_xlat79);
    u_xlat7.z = max(u_xlat79, 1.00000002e-16);
    u_xlat7.xy = u_xlat6.xy * vec2(_NormalScale0);
    u_xlat6.xyz = texture(sampler2D(_Normal1, sampler_Normal0), vs_TEXCOORD1.zw, _GlobalMipBias.x).xyw;
    u_xlat6.x = u_xlat6.x * u_xlat6.z;
    u_xlat6.xy = u_xlat6.xy * vec2(2.0, 2.0) + vec2(-1.0, -1.0);
    u_xlat79 = dot(u_xlat6.xy, u_xlat6.xy);
    u_xlat79 = min(u_xlat79, 1.0);
    u_xlat79 = (-u_xlat79) + 1.0;
    u_xlat79 = sqrt(u_xlat79);
    u_xlat8.z = max(u_xlat79, 1.00000002e-16);
    u_xlat8.xy = u_xlat6.xy * vec2(vec2(_NormalScale1, _NormalScale1));
    u_xlat6.xyz = u_xlat4.yyy * u_xlat8.xyz;
    u_xlat6.xyz = u_xlat4.xxx * u_xlat7.xyz + u_xlat6.xyz;
    u_xlat7.xyz = texture(sampler2D(_Normal2, sampler_Normal0), vs_TEXCOORD2.xy, _GlobalMipBias.x).xyw;
    u_xlat7.x = u_xlat7.x * u_xlat7.z;
    u_xlat7.xy = u_xlat7.xy * vec2(2.0, 2.0) + vec2(-1.0, -1.0);
    u_xlat79 = dot(u_xlat7.xy, u_xlat7.xy);
    u_xlat79 = min(u_xlat79, 1.0);
    u_xlat79 = (-u_xlat79) + 1.0;
    u_xlat79 = sqrt(u_xlat79);
    u_xlat8.z = max(u_xlat79, 1.00000002e-16);
    u_xlat8.xy = u_xlat7.xy * vec2(vec2(_NormalScale2, _NormalScale2));
    u_xlat6.xyz = u_xlat4.zzz * u_xlat8.xyz + u_xlat6.xyz;
    u_xlat7.xyz = texture(sampler2D(_Normal3, sampler_Normal0), vs_TEXCOORD2.zw, _GlobalMipBias.x).xyw;
    u_xlat7.x = u_xlat7.x * u_xlat7.z;
    u_xlat7.xy = u_xlat7.xy * vec2(2.0, 2.0) + vec2(-1.0, -1.0);
    u_xlat79 = dot(u_xlat7.xy, u_xlat7.xy);
    u_xlat79 = min(u_xlat79, 1.0);
    u_xlat79 = (-u_xlat79) + 1.0;
    u_xlat79 = sqrt(u_xlat79);
    u_xlat8.z = max(u_xlat79, 1.00000002e-16);
    u_xlat8.xy = u_xlat7.xy * vec2(vec2(_NormalScale3, _NormalScale3));
    u_xlat6.xyz = u_xlat4.www * u_xlat8.xyz + u_xlat6.xyz;
    u_xlat6.w = u_xlat6.z + 9.99999975e-06;
    u_xlat79 = dot(u_xlat6.xyw, u_xlat6.xyw);
    u_xlat79 = inversesqrt(u_xlat79);
    u_xlat6.xyz = vec3(u_xlat79) * u_xlat6.xyw;
    u_xlat7.x = _MaskMapRemapScale0.y;
    u_xlat7.y = _MaskMapRemapScale1.y;
    u_xlat7.z = _MaskMapRemapScale2.y;
    u_xlat7.w = _MaskMapRemapScale3.y;
    u_xlat8.x = _MaskMapRemapOffset0.y;
    u_xlat8.y = _MaskMapRemapOffset1.y;
    u_xlat8.z = _MaskMapRemapOffset2.y;
    u_xlat8.w = _MaskMapRemapOffset3.y;
    u_xlat7 = u_xlat7 + u_xlat8;
    u_xlat8.x = u_xlat0.z;
    u_xlat8.y = u_xlat1.z;
    u_xlat8.z = u_xlat2.z;
    u_xlat8.w = u_xlat3.y;
    u_xlat8 = (-u_xlat9) * vec4(_Smoothness0, _Smoothness1, _Smoothness2, _Smoothness3) + u_xlat8;
    u_xlat8 = vec4(_LayerHasMask0, _LayerHasMask1, _LayerHasMask2, _LayerHasMask3) * u_xlat8 + u_xlat10;
    u_xlat52 = dot(u_xlat4, u_xlat8);
    u_xlat8.x = u_xlat0.x;
    u_xlat8.y = u_xlat1.x;
    u_xlat8.z = u_xlat2.x;
    u_xlat8.w = u_xlat3.x;
    u_xlat8 = u_xlat8 + (-vec4(_Metallic0, _Metallic1, _Metallic2, _Metallic3));
    u_xlat8 = vec4(_LayerHasMask0, _LayerHasMask1, _LayerHasMask2, _LayerHasMask3) * u_xlat8 + vec4(_Metallic0, _Metallic1, _Metallic2, _Metallic3);
    u_xlat0.x = dot(u_xlat4, u_xlat8);
    u_xlat3.x = u_xlat0.y;
    u_xlat3.y = u_xlat1.y;
    u_xlat3.z = u_xlat2.y;
    u_xlat1 = (-u_xlat7) + u_xlat3;
    u_xlat1 = vec4(_LayerHasMask0, _LayerHasMask1, _LayerHasMask2, _LayerHasMask3) * u_xlat1 + u_xlat7;
    u_xlat26 = dot(u_xlat4, u_xlat1);
    u_xlat1.xyz = u_xlat6.yyy * vs_TEXCOORD5.xyz;
    u_xlat1.xyz = u_xlat6.xxx * (-vs_TEXCOORD4.xyz) + u_xlat1.xyz;
    u_xlat1.xyz = u_xlat6.zzz * vs_TEXCOORD3.xyz + u_xlat1.xyz;
    u_xlat79 = dot(u_xlat1.xyz, u_xlat1.xyz);
    u_xlat79 = inversesqrt(u_xlat79);
    u_xlat1.xyz = vec3(u_xlat79) * u_xlat1.xyz;
    u_xlat79 = vs_TEXCOORD7.y * unity_MatrixV[1].z;
    u_xlat79 = unity_MatrixV[0].z * vs_TEXCOORD7.x + u_xlat79;
    u_xlat79 = unity_MatrixV[2].z * vs_TEXCOORD7.z + u_xlat79;
    u_xlat79 = u_xlat79 + unity_MatrixV[3].z;
    u_xlat79 = (-u_xlat79) + (-_ProjectionParams.y);
    u_xlat79 = max(u_xlat79, 0.0);
    u_xlat79 = u_xlat79 * unity_FogParams.x;
    u_xlat2 = texture(sampler2D(unity_LightmapInd, samplerunity_Lightmap), vs_TEXCOORD0.zw, _GlobalMipBias.x);
    u_xlat3.xyz = texture(sampler2D(unity_Lightmap, samplerunity_Lightmap), vs_TEXCOORD0.zw, _GlobalMipBias.x).xyz;
    u_xlat2.xyz = u_xlat2.xyz + vec3(-0.5, -0.5, -0.5);
    u_xlat2.x = dot(u_xlat1.xyz, u_xlat2.xyz);
    u_xlat2.x = u_xlat2.x + 0.5;
    u_xlat2.xyz = u_xlat2.xxx * u_xlat3.xyz;
    u_xlat80 = max(u_xlat2.w, 9.99999975e-05);
    u_xlat2.xyz = u_xlat2.xyz / vec3(u_xlat80);
    u_xlat80 = (-u_xlat0.x) * 0.959999979 + 0.959999979;
    u_xlat3.x = u_xlat52 + (-u_xlat80);
    u_xlat29.xyz = vec3(u_xlat80) * u_xlat5.xyz;
    u_xlat4.xyz = u_xlat5.xyz + vec3(-0.0399999991, -0.0399999991, -0.0399999991);
    u_xlat4.xyz = u_xlat0.xxx * u_xlat4.xyz + vec3(0.0399999991, 0.0399999991, 0.0399999991);
    u_xlat0.x = (-u_xlat52) + 1.0;
    u_xlat52 = u_xlat0.x * u_xlat0.x;
    u_xlat52 = max(u_xlat52, 0.0078125);
    u_xlat80 = u_xlat52 * u_xlat52;
    u_xlat3.x = u_xlat3.x + 1.0;
    u_xlat3.x = clamp(u_xlat3.x, 0.0, 1.0);
    u_xlat82 = u_xlat52 * 4.0 + 2.0;
    u_xlat26 = min(u_xlat26, 1.0);
    u_xlatb5 = 0.0<_MainLightShadowParams.y;
    if(u_xlatb5){
        u_xlatb5 = _MainLightShadowParams.y==1.0;
        if(u_xlatb5){
            u_xlat5 = vs_TEXCOORD8.xyxy + _MainLightShadowOffset0;
            vec3 txVec0 = vec3(u_xlat5.xy,vs_TEXCOORD8.z);
            u_xlat6.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec0, 0.0);
            vec3 txVec1 = vec3(u_xlat5.zw,vs_TEXCOORD8.z);
            u_xlat6.y = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec1, 0.0);
            u_xlat5 = vs_TEXCOORD8.xyxy + _MainLightShadowOffset1;
            vec3 txVec2 = vec3(u_xlat5.xy,vs_TEXCOORD8.z);
            u_xlat6.z = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec2, 0.0);
            vec3 txVec3 = vec3(u_xlat5.zw,vs_TEXCOORD8.z);
            u_xlat6.w = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec3, 0.0);
            u_xlat5.x = dot(u_xlat6, vec4(0.25, 0.25, 0.25, 0.25));
        } else {
            u_xlatb31 = _MainLightShadowParams.y==2.0;
            if(u_xlatb31){
                u_xlat31.xy = vs_TEXCOORD8.xy * _MainLightShadowmapSize.zw + vec2(0.5, 0.5);
                u_xlat31.xy = floor(u_xlat31.xy);
                u_xlat6.xy = vs_TEXCOORD8.xy * _MainLightShadowmapSize.zw + (-u_xlat31.xy);
                u_xlat7 = u_xlat6.xxyy + vec4(0.5, 1.0, 0.5, 1.0);
                u_xlat8 = u_xlat7.xxzz * u_xlat7.xxzz;
                u_xlat58.xy = u_xlat8.yw * vec2(0.0799999982, 0.0799999982);
                u_xlat7.xz = u_xlat8.xz * vec2(0.5, 0.5) + (-u_xlat6.xy);
                u_xlat8.xy = (-u_xlat6.xy) + vec2(1.0, 1.0);
                u_xlat60.xy = min(u_xlat6.xy, vec2(0.0, 0.0));
                u_xlat60.xy = (-u_xlat60.xy) * u_xlat60.xy + u_xlat8.xy;
                u_xlat6.xy = max(u_xlat6.xy, vec2(0.0, 0.0));
                u_xlat6.xy = (-u_xlat6.xy) * u_xlat6.xy + u_xlat7.yw;
                u_xlat60.xy = u_xlat60.xy + vec2(1.0, 1.0);
                u_xlat6.xy = u_xlat6.xy + vec2(1.0, 1.0);
                u_xlat9.xy = u_xlat7.xz * vec2(0.159999996, 0.159999996);
                u_xlat10.xy = u_xlat8.xy * vec2(0.159999996, 0.159999996);
                u_xlat8.xy = u_xlat60.xy * vec2(0.159999996, 0.159999996);
                u_xlat11.xy = u_xlat6.xy * vec2(0.159999996, 0.159999996);
                u_xlat6.xy = u_xlat7.yw * vec2(0.159999996, 0.159999996);
                u_xlat9.z = u_xlat8.x;
                u_xlat9.w = u_xlat6.x;
                u_xlat10.z = u_xlat11.x;
                u_xlat10.w = u_xlat58.x;
                u_xlat7 = u_xlat9.zwxz + u_xlat10.zwxz;
                u_xlat8.z = u_xlat9.y;
                u_xlat8.w = u_xlat6.y;
                u_xlat11.z = u_xlat10.y;
                u_xlat11.w = u_xlat58.y;
                u_xlat6.xyz = u_xlat8.zyw + u_xlat11.zyw;
                u_xlat8.xyz = u_xlat10.xzw / u_xlat7.zwy;
                u_xlat8.xyz = u_xlat8.xyz + vec3(-2.5, -0.5, 1.5);
                u_xlat9.xyz = u_xlat11.zyw / u_xlat6.xyz;
                u_xlat9.xyz = u_xlat9.xyz + vec3(-2.5, -0.5, 1.5);
                u_xlat8.xyz = u_xlat8.yxz * _MainLightShadowmapSize.xxx;
                u_xlat9.xyz = u_xlat9.xyz * _MainLightShadowmapSize.yyy;
                u_xlat8.w = u_xlat9.x;
                u_xlat10 = u_xlat31.xyxy * _MainLightShadowmapSize.xyxy + u_xlat8.ywxw;
                u_xlat11.xy = u_xlat31.xy * _MainLightShadowmapSize.xy + u_xlat8.zw;
                u_xlat9.w = u_xlat8.y;
                u_xlat8.yw = u_xlat9.yz;
                u_xlat12 = u_xlat31.xyxy * _MainLightShadowmapSize.xyxy + u_xlat8.xyzy;
                u_xlat9 = u_xlat31.xyxy * _MainLightShadowmapSize.xyxy + u_xlat9.wywz;
                u_xlat8 = u_xlat31.xyxy * _MainLightShadowmapSize.xyxy + u_xlat8.xwzw;
                u_xlat13 = u_xlat6.xxxy * u_xlat7.zwyz;
                u_xlat14 = u_xlat6.yyzz * u_xlat7;
                u_xlat31.x = u_xlat6.z * u_xlat7.y;
                vec3 txVec4 = vec3(u_xlat10.xy,vs_TEXCOORD8.z);
                u_xlat57.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec4, 0.0);
                vec3 txVec5 = vec3(u_xlat10.zw,vs_TEXCOORD8.z);
                u_xlat83 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec5, 0.0);
                u_xlat83 = u_xlat83 * u_xlat13.y;
                u_xlat57.x = u_xlat13.x * u_xlat57.x + u_xlat83;
                vec3 txVec6 = vec3(u_xlat11.xy,vs_TEXCOORD8.z);
                u_xlat83 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec6, 0.0);
                u_xlat57.x = u_xlat13.z * u_xlat83 + u_xlat57.x;
                vec3 txVec7 = vec3(u_xlat9.xy,vs_TEXCOORD8.z);
                u_xlat83 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec7, 0.0);
                u_xlat57.x = u_xlat13.w * u_xlat83 + u_xlat57.x;
                vec3 txVec8 = vec3(u_xlat12.xy,vs_TEXCOORD8.z);
                u_xlat83 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec8, 0.0);
                u_xlat57.x = u_xlat14.x * u_xlat83 + u_xlat57.x;
                vec3 txVec9 = vec3(u_xlat12.zw,vs_TEXCOORD8.z);
                u_xlat83 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec9, 0.0);
                u_xlat57.x = u_xlat14.y * u_xlat83 + u_xlat57.x;
                vec3 txVec10 = vec3(u_xlat9.zw,vs_TEXCOORD8.z);
                u_xlat83 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec10, 0.0);
                u_xlat57.x = u_xlat14.z * u_xlat83 + u_xlat57.x;
                vec3 txVec11 = vec3(u_xlat8.xy,vs_TEXCOORD8.z);
                u_xlat83 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec11, 0.0);
                u_xlat57.x = u_xlat14.w * u_xlat83 + u_xlat57.x;
                vec3 txVec12 = vec3(u_xlat8.zw,vs_TEXCOORD8.z);
                u_xlat83 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec12, 0.0);
                u_xlat5.x = u_xlat31.x * u_xlat83 + u_xlat57.x;
            } else {
                u_xlat31.xy = vs_TEXCOORD8.xy * _MainLightShadowmapSize.zw + vec2(0.5, 0.5);
                u_xlat31.xy = floor(u_xlat31.xy);
                u_xlat6.xy = vs_TEXCOORD8.xy * _MainLightShadowmapSize.zw + (-u_xlat31.xy);
                u_xlat7 = u_xlat6.xxyy + vec4(0.5, 1.0, 0.5, 1.0);
                u_xlat8 = u_xlat7.xxzz * u_xlat7.xxzz;
                u_xlat9.yw = u_xlat8.yw * vec2(0.0408160016, 0.0408160016);
                u_xlat58.xy = u_xlat8.xz * vec2(0.5, 0.5) + (-u_xlat6.xy);
                u_xlat7.xz = (-u_xlat6.xy) + vec2(1.0, 1.0);
                u_xlat8.xy = min(u_xlat6.xy, vec2(0.0, 0.0));
                u_xlat7.xz = (-u_xlat8.xy) * u_xlat8.xy + u_xlat7.xz;
                u_xlat8.xy = max(u_xlat6.xy, vec2(0.0, 0.0));
                u_xlat7.yw = (-u_xlat8.xy) * u_xlat8.xy + u_xlat7.yw;
                u_xlat7 = u_xlat7 + vec4(2.0, 2.0, 2.0, 2.0);
                u_xlat8.z = u_xlat7.y * 0.0816320032;
                u_xlat10.xy = u_xlat58.yx * vec2(0.0816320032, 0.0816320032);
                u_xlat58.xy = u_xlat7.xz * vec2(0.0816320032, 0.0816320032);
                u_xlat10.z = u_xlat7.w * 0.0816320032;
                u_xlat8.x = u_xlat10.y;
                u_xlat8.yw = u_xlat6.xx * vec2(-0.0816320032, 0.0816320032) + vec2(0.163264006, 0.0816320032);
                u_xlat7.xz = u_xlat6.xx * vec2(-0.0816320032, 0.0816320032) + vec2(0.0816320032, 0.163264006);
                u_xlat7.y = u_xlat58.x;
                u_xlat7.w = u_xlat9.y;
                u_xlat8 = u_xlat7 + u_xlat8;
                u_xlat10.yw = u_xlat6.yy * vec2(-0.0816320032, 0.0816320032) + vec2(0.163264006, 0.0816320032);
                u_xlat9.xz = u_xlat6.yy * vec2(-0.0816320032, 0.0816320032) + vec2(0.0816320032, 0.163264006);
                u_xlat9.y = u_xlat58.y;
                u_xlat6 = u_xlat9 + u_xlat10;
                u_xlat7 = u_xlat7 / u_xlat8;
                u_xlat7 = u_xlat7 + vec4(-3.5, -1.5, 0.5, 2.5);
                u_xlat9 = u_xlat9 / u_xlat6;
                u_xlat9 = u_xlat9 + vec4(-3.5, -1.5, 0.5, 2.5);
                u_xlat7 = u_xlat7.wxyz * _MainLightShadowmapSize.xxxx;
                u_xlat9 = u_xlat9.xwyz * _MainLightShadowmapSize.yyyy;
                u_xlat10.xzw = u_xlat7.yzw;
                u_xlat10.y = u_xlat9.x;
                u_xlat11 = u_xlat31.xyxy * _MainLightShadowmapSize.xyxy + u_xlat10.xyzy;
                u_xlat12.xy = u_xlat31.xy * _MainLightShadowmapSize.xy + u_xlat10.wy;
                u_xlat7.y = u_xlat10.y;
                u_xlat10.y = u_xlat9.z;
                u_xlat13 = u_xlat31.xyxy * _MainLightShadowmapSize.xyxy + u_xlat10.xyzy;
                u_xlat64.xy = u_xlat31.xy * _MainLightShadowmapSize.xy + u_xlat10.wy;
                u_xlat7.z = u_xlat10.y;
                u_xlat14 = u_xlat31.xyxy * _MainLightShadowmapSize.xyxy + u_xlat7.xyxz;
                u_xlat10.y = u_xlat9.w;
                u_xlat15 = u_xlat31.xyxy * _MainLightShadowmapSize.xyxy + u_xlat10.xyzy;
                u_xlat33.xy = u_xlat31.xy * _MainLightShadowmapSize.xy + u_xlat10.wy;
                u_xlat7.w = u_xlat10.y;
                u_xlat16.xy = u_xlat31.xy * _MainLightShadowmapSize.xy + u_xlat7.xw;
                u_xlat9.xzw = u_xlat10.xzw;
                u_xlat10 = u_xlat31.xyxy * _MainLightShadowmapSize.xyxy + u_xlat9.xyzy;
                u_xlat61.xy = u_xlat31.xy * _MainLightShadowmapSize.xy + u_xlat9.wy;
                u_xlat9.x = u_xlat7.x;
                u_xlat31.xy = u_xlat31.xy * _MainLightShadowmapSize.xy + u_xlat9.xy;
                u_xlat17 = u_xlat6.xxxx * u_xlat8;
                u_xlat18 = u_xlat6.yyyy * u_xlat8;
                u_xlat19 = u_xlat6.zzzz * u_xlat8;
                u_xlat6 = u_xlat6.wwww * u_xlat8;
                vec3 txVec13 = vec3(u_xlat11.xy,vs_TEXCOORD8.z);
                u_xlat83 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec13, 0.0);
                vec3 txVec14 = vec3(u_xlat11.zw,vs_TEXCOORD8.z);
                u_xlat7.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec14, 0.0);
                u_xlat7.x = u_xlat7.x * u_xlat17.y;
                u_xlat83 = u_xlat17.x * u_xlat83 + u_xlat7.x;
                vec3 txVec15 = vec3(u_xlat12.xy,vs_TEXCOORD8.z);
                u_xlat7.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec15, 0.0);
                u_xlat83 = u_xlat17.z * u_xlat7.x + u_xlat83;
                vec3 txVec16 = vec3(u_xlat14.xy,vs_TEXCOORD8.z);
                u_xlat7.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec16, 0.0);
                u_xlat83 = u_xlat17.w * u_xlat7.x + u_xlat83;
                vec3 txVec17 = vec3(u_xlat13.xy,vs_TEXCOORD8.z);
                u_xlat7.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec17, 0.0);
                u_xlat83 = u_xlat18.x * u_xlat7.x + u_xlat83;
                vec3 txVec18 = vec3(u_xlat13.zw,vs_TEXCOORD8.z);
                u_xlat7.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec18, 0.0);
                u_xlat83 = u_xlat18.y * u_xlat7.x + u_xlat83;
                vec3 txVec19 = vec3(u_xlat64.xy,vs_TEXCOORD8.z);
                u_xlat7.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec19, 0.0);
                u_xlat83 = u_xlat18.z * u_xlat7.x + u_xlat83;
                vec3 txVec20 = vec3(u_xlat14.zw,vs_TEXCOORD8.z);
                u_xlat7.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec20, 0.0);
                u_xlat83 = u_xlat18.w * u_xlat7.x + u_xlat83;
                vec3 txVec21 = vec3(u_xlat15.xy,vs_TEXCOORD8.z);
                u_xlat7.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec21, 0.0);
                u_xlat83 = u_xlat19.x * u_xlat7.x + u_xlat83;
                vec3 txVec22 = vec3(u_xlat15.zw,vs_TEXCOORD8.z);
                u_xlat7.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec22, 0.0);
                u_xlat83 = u_xlat19.y * u_xlat7.x + u_xlat83;
                vec3 txVec23 = vec3(u_xlat33.xy,vs_TEXCOORD8.z);
                u_xlat7.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec23, 0.0);
                u_xlat83 = u_xlat19.z * u_xlat7.x + u_xlat83;
                vec3 txVec24 = vec3(u_xlat16.xy,vs_TEXCOORD8.z);
                u_xlat7.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec24, 0.0);
                u_xlat83 = u_xlat19.w * u_xlat7.x + u_xlat83;
                vec3 txVec25 = vec3(u_xlat10.xy,vs_TEXCOORD8.z);
                u_xlat7.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec25, 0.0);
                u_xlat83 = u_xlat6.x * u_xlat7.x + u_xlat83;
                vec3 txVec26 = vec3(u_xlat10.zw,vs_TEXCOORD8.z);
                u_xlat6.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec26, 0.0);
                u_xlat83 = u_xlat6.y * u_xlat6.x + u_xlat83;
                vec3 txVec27 = vec3(u_xlat61.xy,vs_TEXCOORD8.z);
                u_xlat6.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec27, 0.0);
                u_xlat83 = u_xlat6.z * u_xlat6.x + u_xlat83;
                vec3 txVec28 = vec3(u_xlat31.xy,vs_TEXCOORD8.z);
                u_xlat31.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec28, 0.0);
                u_xlat5.x = u_xlat6.w * u_xlat31.x + u_xlat83;
            }
        }
    } else {
        vec3 txVec29 = vec3(vs_TEXCOORD8.xy,vs_TEXCOORD8.z);
        u_xlat5.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec29, 0.0);
    }
    u_xlat31.x = (-_MainLightShadowParams.x) + 1.0;
    u_xlat5.x = u_xlat5.x * _MainLightShadowParams.x + u_xlat31.x;
    u_xlatb31 = 0.0>=vs_TEXCOORD8.z;
    u_xlatb57.x = vs_TEXCOORD8.z>=1.0;
    u_xlatb31 = u_xlatb57.x || u_xlatb31;
    u_xlat5.x = (u_xlatb31) ? 1.0 : u_xlat5.x;
    u_xlat31.xyz = vs_TEXCOORD7.xyz + (-_WorldSpaceCameraPos.xyz);
    u_xlat31.x = dot(u_xlat31.xyz, u_xlat31.xyz);
    u_xlat57.x = u_xlat31.x * _MainLightShadowParams.z + _MainLightShadowParams.w;
    u_xlat57.x = clamp(u_xlat57.x, 0.0, 1.0);
    u_xlat83 = (-u_xlat5.x) + 1.0;
    u_xlat5.x = u_xlat57.x * u_xlat83 + u_xlat5.x;
    u_xlatb57.x = _MainLightCookieTextureFormat!=-1.0;
    if(u_xlatb57.x){
        u_xlat57.xy = vs_TEXCOORD7.yy * _MainLightWorldToLight[1].xy;
        u_xlat57.xy = _MainLightWorldToLight[0].xy * vs_TEXCOORD7.xx + u_xlat57.xy;
        u_xlat57.xy = _MainLightWorldToLight[2].xy * vs_TEXCOORD7.zz + u_xlat57.xy;
        u_xlat57.xy = u_xlat57.xy + _MainLightWorldToLight[3].xy;
        u_xlat57.xy = u_xlat57.xy * vec2(0.5, 0.5) + vec2(0.5, 0.5);
        u_xlat6 = texture(sampler2D(_MainLightCookieTexture, sampler_MainLightCookieTexture), u_xlat57.xy, _GlobalMipBias.x);
        u_xlatb57.xy = equal(vec4(vec4(_MainLightCookieTextureFormat, _MainLightCookieTextureFormat, _MainLightCookieTextureFormat, _MainLightCookieTextureFormat)), vec4(0.0, 1.0, 0.0, 1.0)).xy;
        u_xlat83 = (u_xlatb57.y) ? u_xlat6.w : u_xlat6.x;
        u_xlat6.xyz = (u_xlatb57.x) ? u_xlat6.xyz : vec3(u_xlat83);
    } else {
        u_xlat6.x = float(1.0);
        u_xlat6.y = float(1.0);
        u_xlat6.z = float(1.0);
    }
    u_xlat6.xyz = u_xlat6.xyz * _MainLightColor.xyz;
    u_xlat7.x = vs_TEXCOORD3.w;
    u_xlat7.y = vs_TEXCOORD4.w;
    u_xlat7.z = vs_TEXCOORD5.w;
    u_xlat57.x = dot((-u_xlat7.xyz), u_xlat1.xyz);
    u_xlat57.x = u_xlat57.x + u_xlat57.x;
    u_xlat8.xyz = u_xlat1.xyz * (-u_xlat57.xxx) + (-u_xlat7.xyz);
    u_xlat57.x = dot(u_xlat1.xyz, u_xlat7.xyz);
    u_xlat57.x = clamp(u_xlat57.x, 0.0, 1.0);
    u_xlat57.x = (-u_xlat57.x) + 1.0;
    u_xlat57.x = u_xlat57.x * u_xlat57.x;
    u_xlat57.x = u_xlat57.x * u_xlat57.x;
    u_xlat83 = (-u_xlat0.x) * 0.699999988 + 1.70000005;
    u_xlat0.x = u_xlat0.x * u_xlat83;
    u_xlat0.x = u_xlat0.x * 6.0;
    u_xlat8 = textureLod(samplerCube(unity_SpecCube0, samplerunity_SpecCube0), u_xlat8.xyz, u_xlat0.x);
    u_xlat0.x = u_xlat8.w + -1.0;
    u_xlat0.x = unity_SpecCube0_HDR.w * u_xlat0.x + 1.0;
    u_xlat0.x = max(u_xlat0.x, 0.0);
    u_xlat0.x = log2(u_xlat0.x);
    u_xlat0.x = u_xlat0.x * unity_SpecCube0_HDR.y;
    u_xlat0.x = exp2(u_xlat0.x);
    u_xlat0.x = u_xlat0.x * unity_SpecCube0_HDR.x;
    u_xlat8.xyz = u_xlat8.xyz * u_xlat0.xxx;
    u_xlat0.xz = vec2(u_xlat52) * vec2(u_xlat52) + vec2(-1.0, 1.0);
    u_xlat52 = float(1.0) / u_xlat0.z;
    u_xlat9.xyz = (-u_xlat4.xyz) + u_xlat3.xxx;
    u_xlat9.xyz = u_xlat57.xxx * u_xlat9.xyz + u_xlat4.xyz;
    u_xlat9.xyz = vec3(u_xlat52) * u_xlat9.xyz;
    u_xlat8.xyz = u_xlat8.xyz * u_xlat9.xyz;
    u_xlat2.xyz = u_xlat2.xyz * u_xlat29.xyz + u_xlat8.xyz;
    u_xlat52 = u_xlat5.x * unity_LightData.z;
    u_xlat3.x = dot(u_xlat1.xyz, _MainLightPosition.xyz);
    u_xlat3.x = clamp(u_xlat3.x, 0.0, 1.0);
    u_xlat52 = u_xlat52 * u_xlat3.x;
    u_xlat5.xzw = vec3(u_xlat52) * u_xlat6.xyz;
    u_xlat6.xyz = u_xlat7.xyz + _MainLightPosition.xyz;
    u_xlat52 = dot(u_xlat6.xyz, u_xlat6.xyz);
    u_xlat52 = max(u_xlat52, 1.17549435e-38);
    u_xlat52 = inversesqrt(u_xlat52);
    u_xlat6.xyz = vec3(u_xlat52) * u_xlat6.xyz;
    u_xlat52 = dot(u_xlat1.xyz, u_xlat6.xyz);
    u_xlat52 = clamp(u_xlat52, 0.0, 1.0);
    u_xlat3.x = dot(_MainLightPosition.xyz, u_xlat6.xyz);
    u_xlat3.x = clamp(u_xlat3.x, 0.0, 1.0);
    u_xlat52 = u_xlat52 * u_xlat52;
    u_xlat52 = u_xlat52 * u_xlat0.x + 1.00001001;
    u_xlat3.x = u_xlat3.x * u_xlat3.x;
    u_xlat52 = u_xlat52 * u_xlat52;
    u_xlat3.x = max(u_xlat3.x, 0.100000001);
    u_xlat52 = u_xlat52 * u_xlat3.x;
    u_xlat52 = u_xlat82 * u_xlat52;
    u_xlat52 = u_xlat80 / u_xlat52;
    u_xlat6.xyz = u_xlat4.xyz * vec3(u_xlat52) + u_xlat29.xyz;
    u_xlat5.xzw = u_xlat5.xzw * u_xlat6.xyz;
    u_xlat52 = min(_AdditionalLightsCount.x, unity_LightData.y);
    u_xlatu52 =  uint(int(u_xlat52));
    u_xlat3.x = u_xlat31.x * _AdditionalShadowFadeParams.x + _AdditionalShadowFadeParams.y;
    u_xlat3.x = clamp(u_xlat3.x, 0.0, 1.0);
    u_xlatb6.xy = equal(vec4(vec4(_AdditionalLightsCookieAtlasTextureFormat, _AdditionalLightsCookieAtlasTextureFormat, _AdditionalLightsCookieAtlasTextureFormat, _AdditionalLightsCookieAtlasTextureFormat)), vec4(0.0, 1.0, 0.0, 0.0)).xy;
    u_xlat8.x = float(0.0);
    u_xlat8.y = float(0.0);
    u_xlat8.z = float(0.0);
    for(uint u_xlatu_loop_1 = 0u ; u_xlatu_loop_1<u_xlatu52 ; u_xlatu_loop_1++)
    {
        u_xlatu58 = u_xlatu_loop_1 >> (2u & uint(0x1F));
        u_xlati84 = int(u_xlatu_loop_1 & 3u);
        u_xlat58.x = dot(unity_LightIndices[int(u_xlatu58)], uintBitsToFloat(ImmCB_0[u_xlati84]));
        u_xlati58 = int(u_xlat58.x);
        u_xlat9.xyz = (-vs_TEXCOORD7.xyz) * _AdditionalLightsPosition[u_xlati58].www + _AdditionalLightsPosition[u_xlati58].xyz;
        u_xlat84 = dot(u_xlat9.xyz, u_xlat9.xyz);
        u_xlat84 = max(u_xlat84, 6.10351562e-05);
        u_xlat85 = inversesqrt(u_xlat84);
        u_xlat10.xyz = vec3(u_xlat85) * u_xlat9.xyz;
        u_xlat86 = float(1.0) / float(u_xlat84);
        u_xlat84 = u_xlat84 * _AdditionalLightsAttenuation[u_xlati58].x;
        u_xlat84 = (-u_xlat84) * u_xlat84 + 1.0;
        u_xlat84 = max(u_xlat84, 0.0);
        u_xlat84 = u_xlat84 * u_xlat84;
        u_xlat84 = u_xlat84 * u_xlat86;
        u_xlat86 = dot(_AdditionalLightsSpotDir[u_xlati58].xyz, u_xlat10.xyz);
        u_xlat86 = u_xlat86 * _AdditionalLightsAttenuation[u_xlati58].z + _AdditionalLightsAttenuation[u_xlati58].w;
        u_xlat86 = clamp(u_xlat86, 0.0, 1.0);
        u_xlat86 = u_xlat86 * u_xlat86;
        u_xlat84 = u_xlat84 * u_xlat86;
        u_xlati86 = int(_AdditionalShadowParams[u_xlati58].w);
        u_xlatb87 = u_xlati86>=0;
        if(u_xlatb87){
            u_xlatb87 = vec4(0.0, 0.0, 0.0, 0.0)!=vec4(_AdditionalShadowParams[u_xlati58].z);
            if(u_xlatb87){
                u_xlatb11.xyz = greaterThanEqual(abs(u_xlat10.zzyz), abs(u_xlat10.xyxx)).xyz;
                u_xlatb87 = u_xlatb11.y && u_xlatb11.x;
                u_xlatb11.xyw = lessThan((-u_xlat10.zyzx), vec4(0.0, 0.0, 0.0, 0.0)).xyw;
                u_xlat11.x = (u_xlatb11.x) ? float(5.0) : float(4.0);
                u_xlat11.y = (u_xlatb11.y) ? float(3.0) : float(2.0);
                u_xlat88 = u_xlatb11.w ? 1.0 : float(0.0);
                u_xlat88 = (u_xlatb11.z) ? u_xlat11.y : u_xlat88;
                u_xlat87 = (u_xlatb87) ? u_xlat11.x : u_xlat88;
                u_xlat88 = trunc(_AdditionalShadowParams[u_xlati58].w);
                u_xlat87 = u_xlat87 + u_xlat88;
                u_xlati86 = int(u_xlat87);
            }
            u_xlati86 = u_xlati86 << (2 & int(0x1F));
            u_xlat11 = vs_TEXCOORD7.yyyy * _AdditionalLightsWorldToShadow[(u_xlati86 + 1) / 4][(u_xlati86 + 1) % 4];
            u_xlat11 = _AdditionalLightsWorldToShadow[u_xlati86 / 4][u_xlati86 % 4] * vs_TEXCOORD7.xxxx + u_xlat11;
            u_xlat11 = _AdditionalLightsWorldToShadow[(u_xlati86 + 2) / 4][(u_xlati86 + 2) % 4] * vs_TEXCOORD7.zzzz + u_xlat11;
            u_xlat11 = u_xlat11 + _AdditionalLightsWorldToShadow[(u_xlati86 + 3) / 4][(u_xlati86 + 3) % 4];
            u_xlat11.xyz = u_xlat11.xyz / u_xlat11.www;
            u_xlatb86 = 0.0<_AdditionalShadowParams[u_xlati58].y;
            if(u_xlatb86){
                u_xlatb86 = 1.0==_AdditionalShadowParams[u_xlati58].y;
                if(u_xlatb86){
                    u_xlat12 = u_xlat11.xyxy + _AdditionalShadowOffset0;
                    vec3 txVec30 = vec3(u_xlat12.xy,u_xlat11.z);
                    u_xlat13.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec30, 0.0);
                    vec3 txVec31 = vec3(u_xlat12.zw,u_xlat11.z);
                    u_xlat13.y = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec31, 0.0);
                    u_xlat12 = u_xlat11.xyxy + _AdditionalShadowOffset1;
                    vec3 txVec32 = vec3(u_xlat12.xy,u_xlat11.z);
                    u_xlat13.z = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec32, 0.0);
                    vec3 txVec33 = vec3(u_xlat12.zw,u_xlat11.z);
                    u_xlat13.w = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec33, 0.0);
                    u_xlat86 = dot(u_xlat13, vec4(0.25, 0.25, 0.25, 0.25));
                } else {
                    u_xlatb87 = 2.0==_AdditionalShadowParams[u_xlati58].y;
                    if(u_xlatb87){
                        u_xlat12.xy = u_xlat11.xy * _AdditionalShadowmapSize.zw + vec2(0.5, 0.5);
                        u_xlat12.xy = floor(u_xlat12.xy);
                        u_xlat64.xy = u_xlat11.xy * _AdditionalShadowmapSize.zw + (-u_xlat12.xy);
                        u_xlat13 = u_xlat64.xxyy + vec4(0.5, 1.0, 0.5, 1.0);
                        u_xlat14 = u_xlat13.xxzz * u_xlat13.xxzz;
                        u_xlat13.xz = u_xlat14.yw * vec2(0.0799999982, 0.0799999982);
                        u_xlat14.xy = u_xlat14.xz * vec2(0.5, 0.5) + (-u_xlat64.xy);
                        u_xlat66.xy = (-u_xlat64.xy) + vec2(1.0, 1.0);
                        u_xlat15.xy = min(u_xlat64.xy, vec2(0.0, 0.0));
                        u_xlat15.xy = (-u_xlat15.xy) * u_xlat15.xy + u_xlat66.xy;
                        u_xlat64.xy = max(u_xlat64.xy, vec2(0.0, 0.0));
                        u_xlat64.xy = (-u_xlat64.xy) * u_xlat64.xy + u_xlat13.yw;
                        u_xlat15.xy = u_xlat15.xy + vec2(1.0, 1.0);
                        u_xlat64.xy = u_xlat64.xy + vec2(1.0, 1.0);
                        u_xlat16.xy = u_xlat14.xy * vec2(0.159999996, 0.159999996);
                        u_xlat14.xy = u_xlat66.xy * vec2(0.159999996, 0.159999996);
                        u_xlat15.xy = u_xlat15.xy * vec2(0.159999996, 0.159999996);
                        u_xlat17.xy = u_xlat64.xy * vec2(0.159999996, 0.159999996);
                        u_xlat64.xy = u_xlat13.yw * vec2(0.159999996, 0.159999996);
                        u_xlat16.z = u_xlat15.x;
                        u_xlat16.w = u_xlat64.x;
                        u_xlat14.z = u_xlat17.x;
                        u_xlat14.w = u_xlat13.x;
                        u_xlat18 = u_xlat14.zwxz + u_xlat16.zwxz;
                        u_xlat15.z = u_xlat16.y;
                        u_xlat15.w = u_xlat64.y;
                        u_xlat17.z = u_xlat14.y;
                        u_xlat17.w = u_xlat13.z;
                        u_xlat13.xyz = u_xlat15.zyw + u_xlat17.zyw;
                        u_xlat14.xyz = u_xlat14.xzw / u_xlat18.zwy;
                        u_xlat14.xyz = u_xlat14.xyz + vec3(-2.5, -0.5, 1.5);
                        u_xlat15.xyz = u_xlat17.zyw / u_xlat13.xyz;
                        u_xlat15.xyz = u_xlat15.xyz + vec3(-2.5, -0.5, 1.5);
                        u_xlat14.xyz = u_xlat14.yxz * _AdditionalShadowmapSize.xxx;
                        u_xlat15.xyz = u_xlat15.xyz * _AdditionalShadowmapSize.yyy;
                        u_xlat14.w = u_xlat15.x;
                        u_xlat16 = u_xlat12.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat14.ywxw;
                        u_xlat64.xy = u_xlat12.xy * _AdditionalShadowmapSize.xy + u_xlat14.zw;
                        u_xlat15.w = u_xlat14.y;
                        u_xlat14.yw = u_xlat15.yz;
                        u_xlat17 = u_xlat12.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat14.xyzy;
                        u_xlat15 = u_xlat12.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat15.wywz;
                        u_xlat14 = u_xlat12.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat14.xwzw;
                        u_xlat19 = u_xlat13.xxxy * u_xlat18.zwyz;
                        u_xlat20 = u_xlat13.yyzz * u_xlat18;
                        u_xlat87 = u_xlat13.z * u_xlat18.y;
                        vec3 txVec34 = vec3(u_xlat16.xy,u_xlat11.z);
                        u_xlat88 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec34, 0.0);
                        vec3 txVec35 = vec3(u_xlat16.zw,u_xlat11.z);
                        u_xlat89 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec35, 0.0);
                        u_xlat89 = u_xlat89 * u_xlat19.y;
                        u_xlat88 = u_xlat19.x * u_xlat88 + u_xlat89;
                        vec3 txVec36 = vec3(u_xlat64.xy,u_xlat11.z);
                        u_xlat89 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec36, 0.0);
                        u_xlat88 = u_xlat19.z * u_xlat89 + u_xlat88;
                        vec3 txVec37 = vec3(u_xlat15.xy,u_xlat11.z);
                        u_xlat89 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec37, 0.0);
                        u_xlat88 = u_xlat19.w * u_xlat89 + u_xlat88;
                        vec3 txVec38 = vec3(u_xlat17.xy,u_xlat11.z);
                        u_xlat89 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec38, 0.0);
                        u_xlat88 = u_xlat20.x * u_xlat89 + u_xlat88;
                        vec3 txVec39 = vec3(u_xlat17.zw,u_xlat11.z);
                        u_xlat89 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec39, 0.0);
                        u_xlat88 = u_xlat20.y * u_xlat89 + u_xlat88;
                        vec3 txVec40 = vec3(u_xlat15.zw,u_xlat11.z);
                        u_xlat89 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec40, 0.0);
                        u_xlat88 = u_xlat20.z * u_xlat89 + u_xlat88;
                        vec3 txVec41 = vec3(u_xlat14.xy,u_xlat11.z);
                        u_xlat89 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec41, 0.0);
                        u_xlat88 = u_xlat20.w * u_xlat89 + u_xlat88;
                        vec3 txVec42 = vec3(u_xlat14.zw,u_xlat11.z);
                        u_xlat89 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec42, 0.0);
                        u_xlat86 = u_xlat87 * u_xlat89 + u_xlat88;
                    } else {
                        u_xlat12.xy = u_xlat11.xy * _AdditionalShadowmapSize.zw + vec2(0.5, 0.5);
                        u_xlat12.xy = floor(u_xlat12.xy);
                        u_xlat64.xy = u_xlat11.xy * _AdditionalShadowmapSize.zw + (-u_xlat12.xy);
                        u_xlat13 = u_xlat64.xxyy + vec4(0.5, 1.0, 0.5, 1.0);
                        u_xlat14 = u_xlat13.xxzz * u_xlat13.xxzz;
                        u_xlat15.yw = u_xlat14.yw * vec2(0.0408160016, 0.0408160016);
                        u_xlat13.xz = u_xlat14.xz * vec2(0.5, 0.5) + (-u_xlat64.xy);
                        u_xlat14.xy = (-u_xlat64.xy) + vec2(1.0, 1.0);
                        u_xlat66.xy = min(u_xlat64.xy, vec2(0.0, 0.0));
                        u_xlat14.xy = (-u_xlat66.xy) * u_xlat66.xy + u_xlat14.xy;
                        u_xlat66.xy = max(u_xlat64.xy, vec2(0.0, 0.0));
                        u_xlat39.xz = (-u_xlat66.xy) * u_xlat66.xy + u_xlat13.yw;
                        u_xlat14.xy = u_xlat14.xy + vec2(2.0, 2.0);
                        u_xlat13.yw = u_xlat39.xz + vec2(2.0, 2.0);
                        u_xlat16.z = u_xlat13.y * 0.0816320032;
                        u_xlat17.xyz = u_xlat13.zxw * vec3(0.0816320032, 0.0816320032, 0.0816320032);
                        u_xlat13.xy = u_xlat14.xy * vec2(0.0816320032, 0.0816320032);
                        u_xlat16.x = u_xlat17.y;
                        u_xlat16.yw = u_xlat64.xx * vec2(-0.0816320032, 0.0816320032) + vec2(0.163264006, 0.0816320032);
                        u_xlat14.xz = u_xlat64.xx * vec2(-0.0816320032, 0.0816320032) + vec2(0.0816320032, 0.163264006);
                        u_xlat14.y = u_xlat13.x;
                        u_xlat14.w = u_xlat15.y;
                        u_xlat16 = u_xlat14 + u_xlat16;
                        u_xlat17.yw = u_xlat64.yy * vec2(-0.0816320032, 0.0816320032) + vec2(0.163264006, 0.0816320032);
                        u_xlat15.xz = u_xlat64.yy * vec2(-0.0816320032, 0.0816320032) + vec2(0.0816320032, 0.163264006);
                        u_xlat15.y = u_xlat13.y;
                        u_xlat13 = u_xlat15 + u_xlat17;
                        u_xlat14 = u_xlat14 / u_xlat16;
                        u_xlat14 = u_xlat14 + vec4(-3.5, -1.5, 0.5, 2.5);
                        u_xlat15 = u_xlat15 / u_xlat13;
                        u_xlat15 = u_xlat15 + vec4(-3.5, -1.5, 0.5, 2.5);
                        u_xlat14 = u_xlat14.wxyz * _AdditionalShadowmapSize.xxxx;
                        u_xlat15 = u_xlat15.xwyz * _AdditionalShadowmapSize.yyyy;
                        u_xlat17.xzw = u_xlat14.yzw;
                        u_xlat17.y = u_xlat15.x;
                        u_xlat18 = u_xlat12.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat17.xyzy;
                        u_xlat64.xy = u_xlat12.xy * _AdditionalShadowmapSize.xy + u_xlat17.wy;
                        u_xlat14.y = u_xlat17.y;
                        u_xlat17.y = u_xlat15.z;
                        u_xlat19 = u_xlat12.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat17.xyzy;
                        u_xlat20.xy = u_xlat12.xy * _AdditionalShadowmapSize.xy + u_xlat17.wy;
                        u_xlat14.z = u_xlat17.y;
                        u_xlat21 = u_xlat12.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat14.xyxz;
                        u_xlat17.y = u_xlat15.w;
                        u_xlat22 = u_xlat12.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat17.xyzy;
                        u_xlat40.xy = u_xlat12.xy * _AdditionalShadowmapSize.xy + u_xlat17.wy;
                        u_xlat14.w = u_xlat17.y;
                        u_xlat72.xy = u_xlat12.xy * _AdditionalShadowmapSize.xy + u_xlat14.xw;
                        u_xlat15.xzw = u_xlat17.xzw;
                        u_xlat17 = u_xlat12.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat15.xyzy;
                        u_xlat67.xy = u_xlat12.xy * _AdditionalShadowmapSize.xy + u_xlat15.wy;
                        u_xlat15.x = u_xlat14.x;
                        u_xlat12.xy = u_xlat12.xy * _AdditionalShadowmapSize.xy + u_xlat15.xy;
                        u_xlat23 = u_xlat13.xxxx * u_xlat16;
                        u_xlat24 = u_xlat13.yyyy * u_xlat16;
                        u_xlat25 = u_xlat13.zzzz * u_xlat16;
                        u_xlat13 = u_xlat13.wwww * u_xlat16;
                        vec3 txVec43 = vec3(u_xlat18.xy,u_xlat11.z);
                        u_xlat87 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec43, 0.0);
                        vec3 txVec44 = vec3(u_xlat18.zw,u_xlat11.z);
                        u_xlat88 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec44, 0.0);
                        u_xlat88 = u_xlat88 * u_xlat23.y;
                        u_xlat87 = u_xlat23.x * u_xlat87 + u_xlat88;
                        vec3 txVec45 = vec3(u_xlat64.xy,u_xlat11.z);
                        u_xlat88 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec45, 0.0);
                        u_xlat87 = u_xlat23.z * u_xlat88 + u_xlat87;
                        vec3 txVec46 = vec3(u_xlat21.xy,u_xlat11.z);
                        u_xlat88 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec46, 0.0);
                        u_xlat87 = u_xlat23.w * u_xlat88 + u_xlat87;
                        vec3 txVec47 = vec3(u_xlat19.xy,u_xlat11.z);
                        u_xlat88 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec47, 0.0);
                        u_xlat87 = u_xlat24.x * u_xlat88 + u_xlat87;
                        vec3 txVec48 = vec3(u_xlat19.zw,u_xlat11.z);
                        u_xlat88 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec48, 0.0);
                        u_xlat87 = u_xlat24.y * u_xlat88 + u_xlat87;
                        vec3 txVec49 = vec3(u_xlat20.xy,u_xlat11.z);
                        u_xlat88 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec49, 0.0);
                        u_xlat87 = u_xlat24.z * u_xlat88 + u_xlat87;
                        vec3 txVec50 = vec3(u_xlat21.zw,u_xlat11.z);
                        u_xlat88 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec50, 0.0);
                        u_xlat87 = u_xlat24.w * u_xlat88 + u_xlat87;
                        vec3 txVec51 = vec3(u_xlat22.xy,u_xlat11.z);
                        u_xlat88 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec51, 0.0);
                        u_xlat87 = u_xlat25.x * u_xlat88 + u_xlat87;
                        vec3 txVec52 = vec3(u_xlat22.zw,u_xlat11.z);
                        u_xlat88 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec52, 0.0);
                        u_xlat87 = u_xlat25.y * u_xlat88 + u_xlat87;
                        vec3 txVec53 = vec3(u_xlat40.xy,u_xlat11.z);
                        u_xlat88 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec53, 0.0);
                        u_xlat87 = u_xlat25.z * u_xlat88 + u_xlat87;
                        vec3 txVec54 = vec3(u_xlat72.xy,u_xlat11.z);
                        u_xlat88 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec54, 0.0);
                        u_xlat87 = u_xlat25.w * u_xlat88 + u_xlat87;
                        vec3 txVec55 = vec3(u_xlat17.xy,u_xlat11.z);
                        u_xlat88 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec55, 0.0);
                        u_xlat87 = u_xlat13.x * u_xlat88 + u_xlat87;
                        vec3 txVec56 = vec3(u_xlat17.zw,u_xlat11.z);
                        u_xlat88 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec56, 0.0);
                        u_xlat87 = u_xlat13.y * u_xlat88 + u_xlat87;
                        vec3 txVec57 = vec3(u_xlat67.xy,u_xlat11.z);
                        u_xlat88 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec57, 0.0);
                        u_xlat87 = u_xlat13.z * u_xlat88 + u_xlat87;
                        vec3 txVec58 = vec3(u_xlat12.xy,u_xlat11.z);
                        u_xlat88 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec58, 0.0);
                        u_xlat86 = u_xlat13.w * u_xlat88 + u_xlat87;
                    }
                }
            } else {
                vec3 txVec59 = vec3(u_xlat11.xy,u_xlat11.z);
                u_xlat86 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec59, 0.0);
            }
            u_xlat87 = 1.0 + (-_AdditionalShadowParams[u_xlati58].x);
            u_xlat86 = u_xlat86 * _AdditionalShadowParams[u_xlati58].x + u_xlat87;
            u_xlatb87 = 0.0>=u_xlat11.z;
            u_xlatb88 = u_xlat11.z>=1.0;
            u_xlatb87 = u_xlatb87 || u_xlatb88;
            u_xlat86 = (u_xlatb87) ? 1.0 : u_xlat86;
        } else {
            u_xlat86 = 1.0;
        }
        u_xlat87 = (-u_xlat86) + 1.0;
        u_xlat86 = u_xlat3.x * u_xlat87 + u_xlat86;
        u_xlati87 = 1 << (u_xlati58 & int(0x1F));
        u_xlati87 = int(uint(u_xlati87) & floatBitsToUint(_AdditionalLightsCookieEnableBits));
        if(u_xlati87 != 0) {
            u_xlati87 = int(_AdditionalLightsLightTypes[u_xlati58]);
            u_xlati88 = (u_xlati87 != 0) ? 0 : 1;
            u_xlati11 = u_xlati58 << (2 & int(0x1F));
            if(u_xlati88 != 0) {
                u_xlat37.xyz = vs_TEXCOORD7.yyy * _AdditionalLightsWorldToLights[(u_xlati11 + 1) / 4][(u_xlati11 + 1) % 4].xyw;
                u_xlat37.xyz = _AdditionalLightsWorldToLights[u_xlati11 / 4][u_xlati11 % 4].xyw * vs_TEXCOORD7.xxx + u_xlat37.xyz;
                u_xlat37.xyz = _AdditionalLightsWorldToLights[(u_xlati11 + 2) / 4][(u_xlati11 + 2) % 4].xyw * vs_TEXCOORD7.zzz + u_xlat37.xyz;
                u_xlat37.xyz = u_xlat37.xyz + _AdditionalLightsWorldToLights[(u_xlati11 + 3) / 4][(u_xlati11 + 3) % 4].xyw;
                u_xlat37.xy = u_xlat37.xy / u_xlat37.zz;
                u_xlat37.xy = u_xlat37.xy * vec2(0.5, 0.5) + vec2(0.5, 0.5);
                u_xlat37.xy = clamp(u_xlat37.xy, 0.0, 1.0);
                u_xlat37.xy = _AdditionalLightsCookieAtlasUVRects[u_xlati58].xy * u_xlat37.xy + _AdditionalLightsCookieAtlasUVRects[u_xlati58].zw;
            } else {
                u_xlatb87 = u_xlati87==1;
                u_xlati87 = u_xlatb87 ? 1 : int(0);
                if(u_xlati87 != 0) {
                    u_xlat12.xy = vs_TEXCOORD7.yy * _AdditionalLightsWorldToLights[(u_xlati11 + 1) / 4][(u_xlati11 + 1) % 4].xy;
                    u_xlat12.xy = _AdditionalLightsWorldToLights[u_xlati11 / 4][u_xlati11 % 4].xy * vs_TEXCOORD7.xx + u_xlat12.xy;
                    u_xlat12.xy = _AdditionalLightsWorldToLights[(u_xlati11 + 2) / 4][(u_xlati11 + 2) % 4].xy * vs_TEXCOORD7.zz + u_xlat12.xy;
                    u_xlat12.xy = u_xlat12.xy + _AdditionalLightsWorldToLights[(u_xlati11 + 3) / 4][(u_xlati11 + 3) % 4].xy;
                    u_xlat12.xy = u_xlat12.xy * vec2(0.5, 0.5) + vec2(0.5, 0.5);
                    u_xlat12.xy = fract(u_xlat12.xy);
                    u_xlat37.xy = _AdditionalLightsCookieAtlasUVRects[u_xlati58].xy * u_xlat12.xy + _AdditionalLightsCookieAtlasUVRects[u_xlati58].zw;
                } else {
                    u_xlat12 = vs_TEXCOORD7.yyyy * _AdditionalLightsWorldToLights[(u_xlati11 + 1) / 4][(u_xlati11 + 1) % 4];
                    u_xlat12 = _AdditionalLightsWorldToLights[u_xlati11 / 4][u_xlati11 % 4] * vs_TEXCOORD7.xxxx + u_xlat12;
                    u_xlat12 = _AdditionalLightsWorldToLights[(u_xlati11 + 2) / 4][(u_xlati11 + 2) % 4] * vs_TEXCOORD7.zzzz + u_xlat12;
                    u_xlat12 = u_xlat12 + _AdditionalLightsWorldToLights[(u_xlati11 + 3) / 4][(u_xlati11 + 3) % 4];
                    u_xlat12.xyz = u_xlat12.xyz / u_xlat12.www;
                    u_xlat87 = dot(u_xlat12.xyz, u_xlat12.xyz);
                    u_xlat87 = inversesqrt(u_xlat87);
                    u_xlat12.xyz = vec3(u_xlat87) * u_xlat12.xyz;
                    u_xlat87 = dot(abs(u_xlat12.xyz), vec3(1.0, 1.0, 1.0));
                    u_xlat87 = max(u_xlat87, 9.99999997e-07);
                    u_xlat87 = float(1.0) / float(u_xlat87);
                    u_xlat13.xyz = vec3(u_xlat87) * u_xlat12.zxy;
                    u_xlat13.x = (-u_xlat13.x);
                    u_xlat13.x = clamp(u_xlat13.x, 0.0, 1.0);
                    u_xlatb11.xw = greaterThanEqual(u_xlat13.yyyz, vec4(0.0, 0.0, 0.0, 0.0)).xw;
                    u_xlat11.x = (u_xlatb11.x) ? u_xlat13.x : (-u_xlat13.x);
                    u_xlat11.w = (u_xlatb11.w) ? u_xlat13.x : (-u_xlat13.x);
                    u_xlat11.xw = u_xlat12.xy * vec2(u_xlat87) + u_xlat11.xw;
                    u_xlat11.xw = u_xlat11.xw * vec2(0.5, 0.5) + vec2(0.5, 0.5);
                    u_xlat11.xw = clamp(u_xlat11.xw, 0.0, 1.0);
                    u_xlat37.xy = _AdditionalLightsCookieAtlasUVRects[u_xlati58].xy * u_xlat11.xw + _AdditionalLightsCookieAtlasUVRects[u_xlati58].zw;
                }
            }
            u_xlat11 = textureLod(sampler2D(_AdditionalLightsCookieAtlasTexture, sampler_LinearClamp), u_xlat37.xy, 0.0);
            u_xlat87 = (u_xlatb6.y) ? u_xlat11.w : u_xlat11.x;
            u_xlat11.xyz = (u_xlatb6.x) ? u_xlat11.xyz : vec3(u_xlat87);
        } else {
            u_xlat11.x = float(1.0);
            u_xlat11.y = float(1.0);
            u_xlat11.z = float(1.0);
        }
        u_xlat11.xyz = u_xlat11.xyz * _AdditionalLightsColor[u_xlati58].xyz;
        u_xlat58.x = u_xlat84 * u_xlat86;
        u_xlat84 = dot(u_xlat1.xyz, u_xlat10.xyz);
        u_xlat84 = clamp(u_xlat84, 0.0, 1.0);
        u_xlat58.x = u_xlat84 * u_xlat58.x;
        u_xlat11.xyz = u_xlat58.xxx * u_xlat11.xyz;
        u_xlat9.xyz = u_xlat9.xyz * vec3(u_xlat85) + u_xlat7.xyz;
        u_xlat58.x = dot(u_xlat9.xyz, u_xlat9.xyz);
        u_xlat58.x = max(u_xlat58.x, 1.17549435e-38);
        u_xlat58.x = inversesqrt(u_xlat58.x);
        u_xlat9.xyz = u_xlat58.xxx * u_xlat9.xyz;
        u_xlat58.x = dot(u_xlat1.xyz, u_xlat9.xyz);
        u_xlat58.x = clamp(u_xlat58.x, 0.0, 1.0);
        u_xlat58.y = dot(u_xlat10.xyz, u_xlat9.xyz);
        u_xlat58.y = clamp(u_xlat58.y, 0.0, 1.0);
        u_xlat58.xy = u_xlat58.xy * u_xlat58.xy;
        u_xlat58.x = u_xlat58.x * u_xlat0.x + 1.00001001;
        u_xlat58.x = u_xlat58.x * u_xlat58.x;
        u_xlat84 = max(u_xlat58.y, 0.100000001);
        u_xlat58.x = u_xlat84 * u_xlat58.x;
        u_xlat58.x = u_xlat82 * u_xlat58.x;
        u_xlat58.x = u_xlat80 / u_xlat58.x;
        u_xlat9.xyz = u_xlat4.xyz * u_xlat58.xxx + u_xlat29.xyz;
        u_xlat8.xyz = u_xlat9.xyz * u_xlat11.xyz + u_xlat8.xyz;
    }
    u_xlat0.xyz = u_xlat2.xyz * vec3(u_xlat26) + u_xlat5.xzw;
    u_xlat0.xyz = u_xlat8.xyz + u_xlat0.xyz;
    u_xlat1.x = u_xlat79 * (-u_xlat79);
    u_xlat1.x = exp2(u_xlat1.x);
    u_xlat0.xyz = u_xlat0.xyz * vec3(u_xlat78) + (-unity_FogColor.xyz);
    SV_Target0.xyz = u_xlat1.xxx * u_xlat0.xyz + unity_FogColor.xyz;
    SV_Target0.w = 1.0;
    return;
}

