#version 440
#extension GL_ARB_explicit_attrib_location : require
#extension GL_ARB_shading_language_420pack : require
#ifdef GL_ARB_derivative_control
#extension GL_ARB_derivative_control : enable
#endif

layout(origin_upper_left) in vec4 gl_FragCoord;
#define HLSLCC_ENABLE_UNIFORM_BUFFERS 1
#if HLSLCC_ENABLE_UNIFORM_BUFFERS
#define UNITY_UNIFORM
#else
#define UNITY_UNIFORM uniform
#endif
#define UNITY_SUPPORTS_UNIFORM_LOCATION 1
#if UNITY_SUPPORTS_UNIFORM_LOCATION
#define UNITY_LOCATION(x) layout(location = x)
#define UNITY_BINDING(x) layout(binding = x, std140)
#else
#define UNITY_LOCATION(x)
#define UNITY_BINDING(x) layout(std140)
#endif
precise vec4 u_xlat_precise_vec4;
precise ivec4 u_xlat_precise_ivec4;
precise bvec4 u_xlat_precise_bvec4;
precise uvec4 u_xlat_precise_uvec4;
const uvec4 ImmCB_0[] = uvec4[4] (
	uvec4(0x3F800000, 0x0, 0x0, 0x0),
	uvec4(0x0, 0x3F800000, 0x0, 0x0),
	uvec4(0x0, 0x0, 0x3F800000, 0x0),
	uvec4(0x0, 0x0, 0x0, 0x3F800000));
layout(set = 1, binding = 0, std140) uniform PGlobals {
	vec2 _GlobalMipBias;
	float _AlphaToMaskAvailable;
	vec4 _MainLightPosition;
	vec4 _MainLightColor;
	vec4 _AdditionalLightsCount;
	vec3 _WorldSpaceCameraPos;
	vec4 _ProjectionParams;
	vec4 unity_FogParams;
	vec4 unity_FogColor;
	mat4x4 unity_MatrixV;
	float _DitheringTextureInvSize;
};
layout(set = 1, binding = 1, std140) uniform AdditionalLights {
	vec4 _AdditionalLightsPosition[32];
	vec4 _AdditionalLightsColor[32];
	vec4 _AdditionalLightsAttenuation[32];
	vec4 _AdditionalLightsSpotDir[32];
	vec4 _AdditionalLightsOcclusionProbes[32];
	float _AdditionalLightsLayerMasks[32];
};
layout(set = 1, binding = 2, std140) uniform UnityPerDraw {
	mat4x4 unity_ObjectToWorld;
	mat4x4 unity_WorldToObject;
	vec4 unity_LODFade;
	vec4 unity_WorldTransformParams;
	vec4 unity_RenderingLayer;
	vec4 unity_LightData;
	vec4 unity_LightIndices[2];
	vec4 unity_ProbesOcclusion;
	vec4 unity_SpecCube0_HDR;
	vec4 unity_SpecCube1_HDR;
	vec4 unity_SpecCube0_BoxMax;
	vec4 unity_SpecCube0_BoxMin;
	vec4 unity_SpecCube0_ProbePosition;
	vec4 unity_SpecCube1_BoxMax;
	vec4 unity_SpecCube1_BoxMin;
	vec4 unity_SpecCube1_ProbePosition;
	vec4 unity_LightmapST;
	vec4 unity_DynamicLightmapST;
	vec4 unity_SHAr;
	vec4 unity_SHAg;
	vec4 unity_SHAb;
	vec4 unity_SHBr;
	vec4 unity_SHBg;
	vec4 unity_SHBb;
	vec4 unity_SHC;
	vec4 unity_RendererBounds_Min;
	vec4 unity_RendererBounds_Max;
	mat4x4 unity_MatrixPreviousM;
	mat4x4 unity_MatrixPreviousMI;
	vec4 unity_MotionVectorsParams;
	vec4 unity_SpriteColor;
	vec4 unity_SpriteProps;
};
layout(set = 1, binding = 3, std140) uniform UnityPerMaterial {
	vec4 _BaseMap_ST;
	vec4 _BaseColor;
	vec4 _SpecColor;
	vec4 _EmissionColor;
	float _Cutoff;
	float _Surface;
};
layout(set = 1, binding = 4, std140) uniform LightShadows {
	mat4x4 _MainLightWorldToShadow[5];
	vec4 _CascadeShadowSplitSpheres0;
	vec4 _CascadeShadowSplitSpheres1;
	vec4 _CascadeShadowSplitSpheres2;
	vec4 _CascadeShadowSplitSpheres3;
	vec4 _CascadeShadowSplitSphereRadii;
	vec4 _MainLightShadowOffset0;
	vec4 _MainLightShadowOffset1;
	vec4 _MainLightShadowParams;
	vec4 _MainLightShadowmapSize;
	vec4 _AdditionalShadowOffset0;
	vec4 _AdditionalShadowOffset1;
	vec4 _AdditionalShadowFadeParams;
	vec4 _AdditionalShadowmapSize;
	vec4 _AdditionalShadowParams[32];
	mat4x4 _AdditionalLightsWorldToShadow[32];
};
layout(set = 0, binding = 0) uniform mediump texture2D _BaseMap;
layout(set = 0, binding = 1) uniform mediump texture2D _BumpMap;
layout(set = 0, binding = 2) uniform mediump texture2D _MainLightShadowmapTexture;
layout(set = 0, binding = 3) uniform mediump texture2D _AdditionalLightsShadowmapTexture;
layout(set = 0, binding = 4) uniform mediump texture2D _DitheringTexture;
layout(location = 0) in highp  vec2 vs_TEXCOORD0;
layout(location = 1) in highp  vec3 vs_TEXCOORD1;
layout(location = 2) in highp  vec4 vs_TEXCOORD2;
layout(location = 3) in highp  vec4 vs_TEXCOORD3;
layout(location = 4) in highp  vec4 vs_TEXCOORD4;
layout(location = 5) in highp  vec4 vs_TEXCOORD6;
layout(location = 0) out highp vec4 SV_Target0;
vec4 u_xlat0;
bool u_xlatb0;
vec4 u_xlat1;
bool u_xlatb1;
vec4 u_xlat2;
bool u_xlatb2;
vec3 u_xlat3;
vec3 u_xlat4;
vec4 u_xlat5;
vec4 u_xlat6;
vec4 u_xlat7;
vec4 u_xlat8;
bvec3 u_xlatb8;
vec4 u_xlat9;
bvec3 u_xlatb9;
vec4 u_xlat10;
vec4 u_xlat11;
vec4 u_xlat12;
vec4 u_xlat13;
vec4 u_xlat14;
vec4 u_xlat15;
vec4 u_xlat16;
vec4 u_xlat17;
vec4 u_xlat18;
vec4 u_xlat19;
vec4 u_xlat20;
vec4 u_xlat21;
vec4 u_xlat22;
vec3 u_xlat23;
bool u_xlatb23;
bool u_xlatb25;
vec3 u_xlat29;
vec2 u_xlat30;
vec3 u_xlat31;
bool u_xlatb31;
float u_xlat32;
vec3 u_xlat33;
vec2 u_xlat34;
float u_xlat46;
bool u_xlatb46;
vec2 u_xlat51;
vec2 u_xlat53;
vec2 u_xlat54;
vec2 u_xlat55;
vec2 u_xlat57;
vec2 u_xlat58;
vec2 u_xlat59;
vec2 u_xlat63;
float u_xlat69;
float u_xlat71;
bool u_xlatb71;
float u_xlat72;
uint u_xlatu72;
bool u_xlatb72;
float u_xlat73;
uint u_xlatu73;
float u_xlat74;
int u_xlati74;
uint u_xlatu74;
bool u_xlatb74;
float u_xlat75;
int u_xlati75;
float u_xlat76;
int u_xlati76;
bool u_xlatb76;
float u_xlat77;
bool u_xlatb77;
layout(set = 0, binding = 5) uniform mediump  sampler sampler_BaseMap;
layout(set = 0, binding = 6) uniform mediump  sampler sampler_BumpMap;
layout(set = 0, binding = 7) uniform mediump  sampler sampler_PointRepeat;
layout(set = 0, binding = 8) uniform mediump  samplerShadow sampler_LinearClampCompare;
void main()
{
vec4 hlslcc_FragCoord = vec4(gl_FragCoord.xyz, 1.0/gl_FragCoord.w);
    u_xlat0 = texture(sampler2D(_BaseMap, sampler_BaseMap), vs_TEXCOORD0.xy, _GlobalMipBias.x);
    u_xlat1 = u_xlat0.wxyz * _BaseColor.wxyz;
    u_xlatb0 = u_xlat1.x>=_Cutoff;
    u_xlat0.x = u_xlatb0 ? u_xlat1.x : float(0.0);
    u_xlat23.x = u_xlat0.w * _BaseColor.w + (-_Cutoff);
    u_xlat46 = dFdxCoarse(u_xlat1.x);
    u_xlat69 = dFdyCoarse(u_xlat1.x);
    u_xlat46 = abs(u_xlat69) + abs(u_xlat46);
    u_xlat46 = max(u_xlat46, 9.99999975e-05);
    u_xlat23.x = u_xlat23.x / u_xlat46;
    u_xlat23.x = u_xlat23.x + 0.5;
    u_xlat23.x = clamp(u_xlat23.x, 0.0, 1.0);
    u_xlatb46 = _AlphaToMaskAvailable!=0.0;
    u_xlat0.x = (u_xlatb46) ? u_xlat23.x : u_xlat0.x;
    u_xlat23.x = u_xlat0.x + -9.99999975e-05;
    u_xlatb23 = u_xlat23.x<0.0;
    if(((int(u_xlatb23) * int(0xffffffffu)))!=0){discard;}
    u_xlat2.xyz = texture(sampler2D(_BumpMap, sampler_BumpMap), vs_TEXCOORD0.xy, _GlobalMipBias.x).xyw;
    u_xlat2.x = u_xlat2.x * u_xlat2.z;
    u_xlat23.xz = u_xlat2.xy * vec2(2.0, 2.0) + vec2(-1.0, -1.0);
    u_xlat1.x = dot(u_xlat23.xz, u_xlat23.xz);
    u_xlat1.x = min(u_xlat1.x, 1.0);
    u_xlat1.x = (-u_xlat1.x) + 1.0;
    u_xlat1.x = sqrt(u_xlat1.x);
    u_xlat1.x = max(u_xlat1.x, 1.00000002e-16);
    u_xlat2.xy = hlslcc_FragCoord.xy * vec2(_DitheringTextureInvSize);
    u_xlat2.x = texture(sampler2D(_DitheringTexture, sampler_PointRepeat), u_xlat2.xy, _GlobalMipBias.x).w;
    u_xlatb25 = unity_LODFade.x>=0.0;
    u_xlat2.x = (u_xlatb25) ? abs(u_xlat2.x) : -abs(u_xlat2.x);
    u_xlat2.x = (-u_xlat2.x) + unity_LODFade.x;
    u_xlatb2 = u_xlat2.x<0.0;
    if(((int(u_xlatb2) * int(0xffffffffu)))!=0){discard;}
    u_xlat2.xyz = u_xlat23.zzz * vs_TEXCOORD4.xyz;
    u_xlat2.xyz = u_xlat23.xxx * vs_TEXCOORD3.xyz + u_xlat2.xyz;
    u_xlat2.xyz = u_xlat1.xxx * vs_TEXCOORD2.xyz + u_xlat2.xyz;
    u_xlat23.x = dot(u_xlat2.xyz, u_xlat2.xyz);
    u_xlat23.x = inversesqrt(u_xlat23.x);
    u_xlat2.xyz = u_xlat23.xxx * u_xlat2.xyz;
    u_xlat3.x = vs_TEXCOORD2.w;
    u_xlat3.y = vs_TEXCOORD3.w;
    u_xlat3.z = vs_TEXCOORD4.w;
    u_xlat23.x = dot(u_xlat3.xyz, u_xlat3.xyz);
    u_xlat23.x = max(u_xlat23.x, 6.10351562e-05);
    u_xlat23.x = inversesqrt(u_xlat23.x);
    u_xlat69 = vs_TEXCOORD1.y * unity_MatrixV[1].z;
    u_xlat69 = unity_MatrixV[0].z * vs_TEXCOORD1.x + u_xlat69;
    u_xlat69 = unity_MatrixV[2].z * vs_TEXCOORD1.z + u_xlat69;
    u_xlat69 = u_xlat69 + unity_MatrixV[3].z;
    u_xlat69 = (-u_xlat69) + (-_ProjectionParams.y);
    u_xlat69 = max(u_xlat69, 0.0);
    u_xlat69 = u_xlat69 * unity_FogParams.x;
    u_xlat2.w = 1.0;
    u_xlat4.x = dot(unity_SHAr, u_xlat2);
    u_xlat4.y = dot(unity_SHAg, u_xlat2);
    u_xlat4.z = dot(unity_SHAb, u_xlat2);
    u_xlat5 = u_xlat2.yzzx * u_xlat2.xyzz;
    u_xlat6.x = dot(unity_SHBr, u_xlat5);
    u_xlat6.y = dot(unity_SHBg, u_xlat5);
    u_xlat6.z = dot(unity_SHBb, u_xlat5);
    u_xlat1.x = u_xlat2.y * u_xlat2.y;
    u_xlat1.x = u_xlat2.x * u_xlat2.x + (-u_xlat1.x);
    u_xlat5.xyz = unity_SHC.xyz * u_xlat1.xxx + u_xlat6.xyz;
    u_xlat4.xyz = u_xlat4.xyz + u_xlat5.xyz;
    u_xlat4.xyz = max(u_xlat4.xyz, vec3(0.0, 0.0, 0.0));
    u_xlatb1 = 0.0<_MainLightShadowParams.y;
    if(u_xlatb1){
        u_xlatb1 = _MainLightShadowParams.y==1.0;
        if(u_xlatb1){
            u_xlat5 = vs_TEXCOORD6.xyxy + _MainLightShadowOffset0;
            vec3 txVec0 = vec3(u_xlat5.xy,vs_TEXCOORD6.z);
            u_xlat6.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec0, 0.0);
            vec3 txVec1 = vec3(u_xlat5.zw,vs_TEXCOORD6.z);
            u_xlat6.y = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec1, 0.0);
            u_xlat5 = vs_TEXCOORD6.xyxy + _MainLightShadowOffset1;
            vec3 txVec2 = vec3(u_xlat5.xy,vs_TEXCOORD6.z);
            u_xlat6.z = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec2, 0.0);
            vec3 txVec3 = vec3(u_xlat5.zw,vs_TEXCOORD6.z);
            u_xlat6.w = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec3, 0.0);
            u_xlat1.x = dot(u_xlat6, vec4(0.25, 0.25, 0.25, 0.25));
        } else {
            u_xlatb71 = _MainLightShadowParams.y==2.0;
            if(u_xlatb71){
                u_xlat5.xy = vs_TEXCOORD6.xy * _MainLightShadowmapSize.zw + vec2(0.5, 0.5);
                u_xlat5.xy = floor(u_xlat5.xy);
                u_xlat51.xy = vs_TEXCOORD6.xy * _MainLightShadowmapSize.zw + (-u_xlat5.xy);
                u_xlat6 = u_xlat51.xxyy + vec4(0.5, 1.0, 0.5, 1.0);
                u_xlat7 = u_xlat6.xxzz * u_xlat6.xxzz;
                u_xlat6.xz = u_xlat7.yw * vec2(0.0799999982, 0.0799999982);
                u_xlat7.xy = u_xlat7.xz * vec2(0.5, 0.5) + (-u_xlat51.xy);
                u_xlat53.xy = (-u_xlat51.xy) + vec2(1.0, 1.0);
                u_xlat8.xy = min(u_xlat51.xy, vec2(0.0, 0.0));
                u_xlat8.xy = (-u_xlat8.xy) * u_xlat8.xy + u_xlat53.xy;
                u_xlat51.xy = max(u_xlat51.xy, vec2(0.0, 0.0));
                u_xlat51.xy = (-u_xlat51.xy) * u_xlat51.xy + u_xlat6.yw;
                u_xlat8.xy = u_xlat8.xy + vec2(1.0, 1.0);
                u_xlat51.xy = u_xlat51.xy + vec2(1.0, 1.0);
                u_xlat9.xy = u_xlat7.xy * vec2(0.159999996, 0.159999996);
                u_xlat7.xy = u_xlat53.xy * vec2(0.159999996, 0.159999996);
                u_xlat8.xy = u_xlat8.xy * vec2(0.159999996, 0.159999996);
                u_xlat10.xy = u_xlat51.xy * vec2(0.159999996, 0.159999996);
                u_xlat51.xy = u_xlat6.yw * vec2(0.159999996, 0.159999996);
                u_xlat9.z = u_xlat8.x;
                u_xlat9.w = u_xlat51.x;
                u_xlat7.z = u_xlat10.x;
                u_xlat7.w = u_xlat6.x;
                u_xlat11 = u_xlat7.zwxz + u_xlat9.zwxz;
                u_xlat8.z = u_xlat9.y;
                u_xlat8.w = u_xlat51.y;
                u_xlat10.z = u_xlat7.y;
                u_xlat10.w = u_xlat6.z;
                u_xlat6.xyz = u_xlat8.zyw + u_xlat10.zyw;
                u_xlat7.xyz = u_xlat7.xzw / u_xlat11.zwy;
                u_xlat7.xyz = u_xlat7.xyz + vec3(-2.5, -0.5, 1.5);
                u_xlat8.xyz = u_xlat10.zyw / u_xlat6.xyz;
                u_xlat8.xyz = u_xlat8.xyz + vec3(-2.5, -0.5, 1.5);
                u_xlat7.xyz = u_xlat7.yxz * _MainLightShadowmapSize.xxx;
                u_xlat8.xyz = u_xlat8.xyz * _MainLightShadowmapSize.yyy;
                u_xlat7.w = u_xlat8.x;
                u_xlat9 = u_xlat5.xyxy * _MainLightShadowmapSize.xyxy + u_xlat7.ywxw;
                u_xlat51.xy = u_xlat5.xy * _MainLightShadowmapSize.xy + u_xlat7.zw;
                u_xlat8.w = u_xlat7.y;
                u_xlat7.yw = u_xlat8.yz;
                u_xlat10 = u_xlat5.xyxy * _MainLightShadowmapSize.xyxy + u_xlat7.xyzy;
                u_xlat8 = u_xlat5.xyxy * _MainLightShadowmapSize.xyxy + u_xlat8.wywz;
                u_xlat7 = u_xlat5.xyxy * _MainLightShadowmapSize.xyxy + u_xlat7.xwzw;
                u_xlat12 = u_xlat6.xxxy * u_xlat11.zwyz;
                u_xlat13 = u_xlat6.yyzz * u_xlat11;
                u_xlat71 = u_xlat6.z * u_xlat11.y;
                vec3 txVec4 = vec3(u_xlat9.xy,vs_TEXCOORD6.z);
                u_xlat72 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec4, 0.0);
                vec3 txVec5 = vec3(u_xlat9.zw,vs_TEXCOORD6.z);
                u_xlat73 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec5, 0.0);
                u_xlat73 = u_xlat73 * u_xlat12.y;
                u_xlat72 = u_xlat12.x * u_xlat72 + u_xlat73;
                vec3 txVec6 = vec3(u_xlat51.xy,vs_TEXCOORD6.z);
                u_xlat73 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec6, 0.0);
                u_xlat72 = u_xlat12.z * u_xlat73 + u_xlat72;
                vec3 txVec7 = vec3(u_xlat8.xy,vs_TEXCOORD6.z);
                u_xlat73 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec7, 0.0);
                u_xlat72 = u_xlat12.w * u_xlat73 + u_xlat72;
                vec3 txVec8 = vec3(u_xlat10.xy,vs_TEXCOORD6.z);
                u_xlat73 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec8, 0.0);
                u_xlat72 = u_xlat13.x * u_xlat73 + u_xlat72;
                vec3 txVec9 = vec3(u_xlat10.zw,vs_TEXCOORD6.z);
                u_xlat73 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec9, 0.0);
                u_xlat72 = u_xlat13.y * u_xlat73 + u_xlat72;
                vec3 txVec10 = vec3(u_xlat8.zw,vs_TEXCOORD6.z);
                u_xlat73 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec10, 0.0);
                u_xlat72 = u_xlat13.z * u_xlat73 + u_xlat72;
                vec3 txVec11 = vec3(u_xlat7.xy,vs_TEXCOORD6.z);
                u_xlat73 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec11, 0.0);
                u_xlat72 = u_xlat13.w * u_xlat73 + u_xlat72;
                vec3 txVec12 = vec3(u_xlat7.zw,vs_TEXCOORD6.z);
                u_xlat73 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec12, 0.0);
                u_xlat1.x = u_xlat71 * u_xlat73 + u_xlat72;
            } else {
                u_xlat5.xy = vs_TEXCOORD6.xy * _MainLightShadowmapSize.zw + vec2(0.5, 0.5);
                u_xlat5.xy = floor(u_xlat5.xy);
                u_xlat51.xy = vs_TEXCOORD6.xy * _MainLightShadowmapSize.zw + (-u_xlat5.xy);
                u_xlat6 = u_xlat51.xxyy + vec4(0.5, 1.0, 0.5, 1.0);
                u_xlat7 = u_xlat6.xxzz * u_xlat6.xxzz;
                u_xlat8.yw = u_xlat7.yw * vec2(0.0408160016, 0.0408160016);
                u_xlat6.xz = u_xlat7.xz * vec2(0.5, 0.5) + (-u_xlat51.xy);
                u_xlat7.xy = (-u_xlat51.xy) + vec2(1.0, 1.0);
                u_xlat53.xy = min(u_xlat51.xy, vec2(0.0, 0.0));
                u_xlat7.xy = (-u_xlat53.xy) * u_xlat53.xy + u_xlat7.xy;
                u_xlat53.xy = max(u_xlat51.xy, vec2(0.0, 0.0));
                u_xlat29.xz = (-u_xlat53.xy) * u_xlat53.xy + u_xlat6.yw;
                u_xlat7.xy = u_xlat7.xy + vec2(2.0, 2.0);
                u_xlat6.yw = u_xlat29.xz + vec2(2.0, 2.0);
                u_xlat9.z = u_xlat6.y * 0.0816320032;
                u_xlat10.xyz = u_xlat6.zxw * vec3(0.0816320032, 0.0816320032, 0.0816320032);
                u_xlat6.xy = u_xlat7.xy * vec2(0.0816320032, 0.0816320032);
                u_xlat9.x = u_xlat10.y;
                u_xlat9.yw = u_xlat51.xx * vec2(-0.0816320032, 0.0816320032) + vec2(0.163264006, 0.0816320032);
                u_xlat7.xz = u_xlat51.xx * vec2(-0.0816320032, 0.0816320032) + vec2(0.0816320032, 0.163264006);
                u_xlat7.y = u_xlat6.x;
                u_xlat7.w = u_xlat8.y;
                u_xlat9 = u_xlat7 + u_xlat9;
                u_xlat10.yw = u_xlat51.yy * vec2(-0.0816320032, 0.0816320032) + vec2(0.163264006, 0.0816320032);
                u_xlat8.xz = u_xlat51.yy * vec2(-0.0816320032, 0.0816320032) + vec2(0.0816320032, 0.163264006);
                u_xlat8.y = u_xlat6.y;
                u_xlat6 = u_xlat8 + u_xlat10;
                u_xlat7 = u_xlat7 / u_xlat9;
                u_xlat7 = u_xlat7 + vec4(-3.5, -1.5, 0.5, 2.5);
                u_xlat8 = u_xlat8 / u_xlat6;
                u_xlat8 = u_xlat8 + vec4(-3.5, -1.5, 0.5, 2.5);
                u_xlat7 = u_xlat7.wxyz * _MainLightShadowmapSize.xxxx;
                u_xlat8 = u_xlat8.xwyz * _MainLightShadowmapSize.yyyy;
                u_xlat10.xzw = u_xlat7.yzw;
                u_xlat10.y = u_xlat8.x;
                u_xlat11 = u_xlat5.xyxy * _MainLightShadowmapSize.xyxy + u_xlat10.xyzy;
                u_xlat51.xy = u_xlat5.xy * _MainLightShadowmapSize.xy + u_xlat10.wy;
                u_xlat7.y = u_xlat10.y;
                u_xlat10.y = u_xlat8.z;
                u_xlat12 = u_xlat5.xyxy * _MainLightShadowmapSize.xyxy + u_xlat10.xyzy;
                u_xlat13.xy = u_xlat5.xy * _MainLightShadowmapSize.xy + u_xlat10.wy;
                u_xlat7.z = u_xlat10.y;
                u_xlat14 = u_xlat5.xyxy * _MainLightShadowmapSize.xyxy + u_xlat7.xyxz;
                u_xlat10.y = u_xlat8.w;
                u_xlat15 = u_xlat5.xyxy * _MainLightShadowmapSize.xyxy + u_xlat10.xyzy;
                u_xlat30.xy = u_xlat5.xy * _MainLightShadowmapSize.xy + u_xlat10.wy;
                u_xlat7.w = u_xlat10.y;
                u_xlat59.xy = u_xlat5.xy * _MainLightShadowmapSize.xy + u_xlat7.xw;
                u_xlat8.xzw = u_xlat10.xzw;
                u_xlat10 = u_xlat5.xyxy * _MainLightShadowmapSize.xyxy + u_xlat8.xyzy;
                u_xlat54.xy = u_xlat5.xy * _MainLightShadowmapSize.xy + u_xlat8.wy;
                u_xlat8.x = u_xlat7.x;
                u_xlat5.xy = u_xlat5.xy * _MainLightShadowmapSize.xy + u_xlat8.xy;
                u_xlat16 = u_xlat6.xxxx * u_xlat9;
                u_xlat17 = u_xlat6.yyyy * u_xlat9;
                u_xlat18 = u_xlat6.zzzz * u_xlat9;
                u_xlat6 = u_xlat6.wwww * u_xlat9;
                vec3 txVec13 = vec3(u_xlat11.xy,vs_TEXCOORD6.z);
                u_xlat71 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec13, 0.0);
                vec3 txVec14 = vec3(u_xlat11.zw,vs_TEXCOORD6.z);
                u_xlat72 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec14, 0.0);
                u_xlat72 = u_xlat72 * u_xlat16.y;
                u_xlat71 = u_xlat16.x * u_xlat71 + u_xlat72;
                vec3 txVec15 = vec3(u_xlat51.xy,vs_TEXCOORD6.z);
                u_xlat72 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec15, 0.0);
                u_xlat71 = u_xlat16.z * u_xlat72 + u_xlat71;
                vec3 txVec16 = vec3(u_xlat14.xy,vs_TEXCOORD6.z);
                u_xlat72 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec16, 0.0);
                u_xlat71 = u_xlat16.w * u_xlat72 + u_xlat71;
                vec3 txVec17 = vec3(u_xlat12.xy,vs_TEXCOORD6.z);
                u_xlat72 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec17, 0.0);
                u_xlat71 = u_xlat17.x * u_xlat72 + u_xlat71;
                vec3 txVec18 = vec3(u_xlat12.zw,vs_TEXCOORD6.z);
                u_xlat72 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec18, 0.0);
                u_xlat71 = u_xlat17.y * u_xlat72 + u_xlat71;
                vec3 txVec19 = vec3(u_xlat13.xy,vs_TEXCOORD6.z);
                u_xlat72 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec19, 0.0);
                u_xlat71 = u_xlat17.z * u_xlat72 + u_xlat71;
                vec3 txVec20 = vec3(u_xlat14.zw,vs_TEXCOORD6.z);
                u_xlat72 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec20, 0.0);
                u_xlat71 = u_xlat17.w * u_xlat72 + u_xlat71;
                vec3 txVec21 = vec3(u_xlat15.xy,vs_TEXCOORD6.z);
                u_xlat72 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec21, 0.0);
                u_xlat71 = u_xlat18.x * u_xlat72 + u_xlat71;
                vec3 txVec22 = vec3(u_xlat15.zw,vs_TEXCOORD6.z);
                u_xlat72 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec22, 0.0);
                u_xlat71 = u_xlat18.y * u_xlat72 + u_xlat71;
                vec3 txVec23 = vec3(u_xlat30.xy,vs_TEXCOORD6.z);
                u_xlat72 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec23, 0.0);
                u_xlat71 = u_xlat18.z * u_xlat72 + u_xlat71;
                vec3 txVec24 = vec3(u_xlat59.xy,vs_TEXCOORD6.z);
                u_xlat72 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec24, 0.0);
                u_xlat71 = u_xlat18.w * u_xlat72 + u_xlat71;
                vec3 txVec25 = vec3(u_xlat10.xy,vs_TEXCOORD6.z);
                u_xlat72 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec25, 0.0);
                u_xlat71 = u_xlat6.x * u_xlat72 + u_xlat71;
                vec3 txVec26 = vec3(u_xlat10.zw,vs_TEXCOORD6.z);
                u_xlat72 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec26, 0.0);
                u_xlat71 = u_xlat6.y * u_xlat72 + u_xlat71;
                vec3 txVec27 = vec3(u_xlat54.xy,vs_TEXCOORD6.z);
                u_xlat72 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec27, 0.0);
                u_xlat71 = u_xlat6.z * u_xlat72 + u_xlat71;
                vec3 txVec28 = vec3(u_xlat5.xy,vs_TEXCOORD6.z);
                u_xlat72 = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec28, 0.0);
                u_xlat1.x = u_xlat6.w * u_xlat72 + u_xlat71;
            }
        }
    } else {
        vec3 txVec29 = vec3(vs_TEXCOORD6.xy,vs_TEXCOORD6.z);
        u_xlat1.x = textureLod(sampler2DShadow(_MainLightShadowmapTexture, sampler_LinearClampCompare), txVec29, 0.0);
    }
    u_xlat71 = (-_MainLightShadowParams.x) + 1.0;
    u_xlat1.x = u_xlat1.x * _MainLightShadowParams.x + u_xlat71;
    u_xlatb71 = 0.0>=vs_TEXCOORD6.z;
    u_xlatb72 = vs_TEXCOORD6.z>=1.0;
    u_xlatb71 = u_xlatb71 || u_xlatb72;
    u_xlat1.x = (u_xlatb71) ? 1.0 : u_xlat1.x;
    u_xlat5.xyz = vs_TEXCOORD1.xyz + (-_WorldSpaceCameraPos.xyz);
    u_xlat71 = dot(u_xlat5.xyz, u_xlat5.xyz);
    u_xlat72 = u_xlat71 * _MainLightShadowParams.z + _MainLightShadowParams.w;
    u_xlat72 = clamp(u_xlat72, 0.0, 1.0);
    u_xlat73 = (-u_xlat1.x) + 1.0;
    u_xlat1.x = u_xlat72 * u_xlat73 + u_xlat1.x;
    u_xlat1.x = u_xlat1.x * unity_LightData.z;
    u_xlat5.xyz = u_xlat1.xxx * _MainLightColor.xyz;
    u_xlat1.x = dot(u_xlat2.xyz, _MainLightPosition.xyz);
    u_xlat1.x = clamp(u_xlat1.x, 0.0, 1.0);
    u_xlat6.xyz = u_xlat1.xxx * u_xlat5.xyz;
    u_xlat1.x = _SpecColor.w * 10.0 + 1.0;
    u_xlat1.x = exp2(u_xlat1.x);
    u_xlat7.xyz = u_xlat3.xyz * u_xlat23.xxx + _MainLightPosition.xyz;
    u_xlat72 = dot(u_xlat7.xyz, u_xlat7.xyz);
    u_xlat72 = max(u_xlat72, 1.17549435e-38);
    u_xlat72 = inversesqrt(u_xlat72);
    u_xlat7.xyz = vec3(u_xlat72) * u_xlat7.xyz;
    u_xlat72 = dot(u_xlat2.xyz, u_xlat7.xyz);
    u_xlat72 = clamp(u_xlat72, 0.0, 1.0);
    u_xlat72 = log2(u_xlat72);
    u_xlat72 = u_xlat1.x * u_xlat72;
    u_xlat72 = exp2(u_xlat72);
    u_xlat7.xyz = vec3(u_xlat72) * _SpecColor.xyz;
    u_xlat5.xyz = u_xlat5.xyz * u_xlat7.xyz;
    u_xlat5.xyz = u_xlat6.xyz * u_xlat1.yzw + u_xlat5.xyz;
    u_xlat72 = min(_AdditionalLightsCount.x, unity_LightData.y);
    u_xlatu72 =  uint(int(u_xlat72));
    u_xlat71 = u_xlat71 * _AdditionalShadowFadeParams.x + _AdditionalShadowFadeParams.y;
    u_xlat71 = clamp(u_xlat71, 0.0, 1.0);
    u_xlat6.x = float(0.0);
    u_xlat6.y = float(0.0);
    u_xlat6.z = float(0.0);
    for(uint u_xlatu_loop_1 = 0u ; u_xlatu_loop_1<u_xlatu72 ; u_xlatu_loop_1++)
    {
        u_xlatu74 = u_xlatu_loop_1 >> (2u & uint(0x1F));
        u_xlati75 = int(u_xlatu_loop_1 & 3u);
        u_xlat74 = dot(unity_LightIndices[int(u_xlatu74)], uintBitsToFloat(ImmCB_0[u_xlati75]));
        u_xlati74 = int(u_xlat74);
        u_xlat7.xyz = (-vs_TEXCOORD1.xyz) * _AdditionalLightsPosition[u_xlati74].www + _AdditionalLightsPosition[u_xlati74].xyz;
        u_xlat75 = dot(u_xlat7.xyz, u_xlat7.xyz);
        u_xlat75 = max(u_xlat75, 6.10351562e-05);
        u_xlat76 = inversesqrt(u_xlat75);
        u_xlat7.xyz = vec3(u_xlat76) * u_xlat7.xyz;
        u_xlat76 = float(1.0) / float(u_xlat75);
        u_xlat75 = u_xlat75 * _AdditionalLightsAttenuation[u_xlati74].x;
        u_xlat75 = (-u_xlat75) * u_xlat75 + 1.0;
        u_xlat75 = max(u_xlat75, 0.0);
        u_xlat75 = u_xlat75 * u_xlat75;
        u_xlat75 = u_xlat75 * u_xlat76;
        u_xlat76 = dot(_AdditionalLightsSpotDir[u_xlati74].xyz, u_xlat7.xyz);
        u_xlat76 = u_xlat76 * _AdditionalLightsAttenuation[u_xlati74].z + _AdditionalLightsAttenuation[u_xlati74].w;
        u_xlat76 = clamp(u_xlat76, 0.0, 1.0);
        u_xlat76 = u_xlat76 * u_xlat76;
        u_xlat75 = u_xlat75 * u_xlat76;
        u_xlati76 = int(_AdditionalShadowParams[u_xlati74].w);
        u_xlatb8.x = u_xlati76>=0;
        if(u_xlatb8.x){
            u_xlatb8.x = vec4(0.0, 0.0, 0.0, 0.0)!=vec4(_AdditionalShadowParams[u_xlati74].z);
            if(u_xlatb8.x){
                u_xlatb8.xyz = greaterThanEqual(abs(u_xlat7.zzyz), abs(u_xlat7.xyxx)).xyz;
                u_xlatb8.x = u_xlatb8.y && u_xlatb8.x;
                u_xlatb9.xyz = lessThan((-u_xlat7.zyxz), vec4(0.0, 0.0, 0.0, 0.0)).xyz;
                u_xlat31.x = (u_xlatb9.x) ? float(5.0) : float(4.0);
                u_xlat31.z = (u_xlatb9.y) ? float(3.0) : float(2.0);
                u_xlat9.x = u_xlatb9.z ? 1.0 : float(0.0);
                u_xlat54.x = (u_xlatb8.z) ? u_xlat31.z : u_xlat9.x;
                u_xlat8.x = (u_xlatb8.x) ? u_xlat31.x : u_xlat54.x;
                u_xlat31.x = trunc(_AdditionalShadowParams[u_xlati74].w);
                u_xlat8.x = u_xlat8.x + u_xlat31.x;
                u_xlati76 = int(u_xlat8.x);
            }
            u_xlati76 = u_xlati76 << (2 & int(0x1F));
            u_xlat8 = vs_TEXCOORD1.yyyy * _AdditionalLightsWorldToShadow[(u_xlati76 + 1) / 4][(u_xlati76 + 1) % 4];
            u_xlat8 = _AdditionalLightsWorldToShadow[u_xlati76 / 4][u_xlati76 % 4] * vs_TEXCOORD1.xxxx + u_xlat8;
            u_xlat8 = _AdditionalLightsWorldToShadow[(u_xlati76 + 2) / 4][(u_xlati76 + 2) % 4] * vs_TEXCOORD1.zzzz + u_xlat8;
            u_xlat8 = u_xlat8 + _AdditionalLightsWorldToShadow[(u_xlati76 + 3) / 4][(u_xlati76 + 3) % 4];
            u_xlat8.xyz = u_xlat8.xyz / u_xlat8.www;
            u_xlatb76 = 0.0<_AdditionalShadowParams[u_xlati74].y;
            if(u_xlatb76){
                u_xlatb76 = 1.0==_AdditionalShadowParams[u_xlati74].y;
                if(u_xlatb76){
                    u_xlat9 = u_xlat8.xyxy + _AdditionalShadowOffset0;
                    vec3 txVec30 = vec3(u_xlat9.xy,u_xlat8.z);
                    u_xlat10.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec30, 0.0);
                    vec3 txVec31 = vec3(u_xlat9.zw,u_xlat8.z);
                    u_xlat10.y = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec31, 0.0);
                    u_xlat9 = u_xlat8.xyxy + _AdditionalShadowOffset1;
                    vec3 txVec32 = vec3(u_xlat9.xy,u_xlat8.z);
                    u_xlat10.z = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec32, 0.0);
                    vec3 txVec33 = vec3(u_xlat9.zw,u_xlat8.z);
                    u_xlat10.w = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec33, 0.0);
                    u_xlat76 = dot(u_xlat10, vec4(0.25, 0.25, 0.25, 0.25));
                } else {
                    u_xlatb77 = 2.0==_AdditionalShadowParams[u_xlati74].y;
                    if(u_xlatb77){
                        u_xlat9.xy = u_xlat8.xy * _AdditionalShadowmapSize.zw + vec2(0.5, 0.5);
                        u_xlat9.xy = floor(u_xlat9.xy);
                        u_xlat55.xy = u_xlat8.xy * _AdditionalShadowmapSize.zw + (-u_xlat9.xy);
                        u_xlat10 = u_xlat55.xxyy + vec4(0.5, 1.0, 0.5, 1.0);
                        u_xlat11 = u_xlat10.xxzz * u_xlat10.xxzz;
                        u_xlat10.xz = u_xlat11.yw * vec2(0.0799999982, 0.0799999982);
                        u_xlat11.xy = u_xlat11.xz * vec2(0.5, 0.5) + (-u_xlat55.xy);
                        u_xlat57.xy = (-u_xlat55.xy) + vec2(1.0, 1.0);
                        u_xlat12.xy = min(u_xlat55.xy, vec2(0.0, 0.0));
                        u_xlat12.xy = (-u_xlat12.xy) * u_xlat12.xy + u_xlat57.xy;
                        u_xlat55.xy = max(u_xlat55.xy, vec2(0.0, 0.0));
                        u_xlat55.xy = (-u_xlat55.xy) * u_xlat55.xy + u_xlat10.yw;
                        u_xlat12.xy = u_xlat12.xy + vec2(1.0, 1.0);
                        u_xlat55.xy = u_xlat55.xy + vec2(1.0, 1.0);
                        u_xlat13.xy = u_xlat11.xy * vec2(0.159999996, 0.159999996);
                        u_xlat11.xy = u_xlat57.xy * vec2(0.159999996, 0.159999996);
                        u_xlat12.xy = u_xlat12.xy * vec2(0.159999996, 0.159999996);
                        u_xlat14.xy = u_xlat55.xy * vec2(0.159999996, 0.159999996);
                        u_xlat55.xy = u_xlat10.yw * vec2(0.159999996, 0.159999996);
                        u_xlat13.z = u_xlat12.x;
                        u_xlat13.w = u_xlat55.x;
                        u_xlat11.z = u_xlat14.x;
                        u_xlat11.w = u_xlat10.x;
                        u_xlat15 = u_xlat11.zwxz + u_xlat13.zwxz;
                        u_xlat12.z = u_xlat13.y;
                        u_xlat12.w = u_xlat55.y;
                        u_xlat14.z = u_xlat11.y;
                        u_xlat14.w = u_xlat10.z;
                        u_xlat10.xyz = u_xlat12.zyw + u_xlat14.zyw;
                        u_xlat11.xyz = u_xlat11.xzw / u_xlat15.zwy;
                        u_xlat11.xyz = u_xlat11.xyz + vec3(-2.5, -0.5, 1.5);
                        u_xlat12.xyz = u_xlat14.zyw / u_xlat10.xyz;
                        u_xlat12.xyz = u_xlat12.xyz + vec3(-2.5, -0.5, 1.5);
                        u_xlat11.xyz = u_xlat11.yxz * _AdditionalShadowmapSize.xxx;
                        u_xlat12.xyz = u_xlat12.xyz * _AdditionalShadowmapSize.yyy;
                        u_xlat11.w = u_xlat12.x;
                        u_xlat13 = u_xlat9.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat11.ywxw;
                        u_xlat55.xy = u_xlat9.xy * _AdditionalShadowmapSize.xy + u_xlat11.zw;
                        u_xlat12.w = u_xlat11.y;
                        u_xlat11.yw = u_xlat12.yz;
                        u_xlat14 = u_xlat9.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat11.xyzy;
                        u_xlat12 = u_xlat9.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat12.wywz;
                        u_xlat11 = u_xlat9.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat11.xwzw;
                        u_xlat16 = u_xlat10.xxxy * u_xlat15.zwyz;
                        u_xlat17 = u_xlat10.yyzz * u_xlat15;
                        u_xlat77 = u_xlat10.z * u_xlat15.y;
                        vec3 txVec34 = vec3(u_xlat13.xy,u_xlat8.z);
                        u_xlat9.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec34, 0.0);
                        vec3 txVec35 = vec3(u_xlat13.zw,u_xlat8.z);
                        u_xlat32 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec35, 0.0);
                        u_xlat32 = u_xlat32 * u_xlat16.y;
                        u_xlat9.x = u_xlat16.x * u_xlat9.x + u_xlat32;
                        vec3 txVec36 = vec3(u_xlat55.xy,u_xlat8.z);
                        u_xlat32 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec36, 0.0);
                        u_xlat9.x = u_xlat16.z * u_xlat32 + u_xlat9.x;
                        vec3 txVec37 = vec3(u_xlat12.xy,u_xlat8.z);
                        u_xlat32 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec37, 0.0);
                        u_xlat9.x = u_xlat16.w * u_xlat32 + u_xlat9.x;
                        vec3 txVec38 = vec3(u_xlat14.xy,u_xlat8.z);
                        u_xlat32 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec38, 0.0);
                        u_xlat9.x = u_xlat17.x * u_xlat32 + u_xlat9.x;
                        vec3 txVec39 = vec3(u_xlat14.zw,u_xlat8.z);
                        u_xlat32 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec39, 0.0);
                        u_xlat9.x = u_xlat17.y * u_xlat32 + u_xlat9.x;
                        vec3 txVec40 = vec3(u_xlat12.zw,u_xlat8.z);
                        u_xlat32 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec40, 0.0);
                        u_xlat9.x = u_xlat17.z * u_xlat32 + u_xlat9.x;
                        vec3 txVec41 = vec3(u_xlat11.xy,u_xlat8.z);
                        u_xlat32 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec41, 0.0);
                        u_xlat9.x = u_xlat17.w * u_xlat32 + u_xlat9.x;
                        vec3 txVec42 = vec3(u_xlat11.zw,u_xlat8.z);
                        u_xlat32 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec42, 0.0);
                        u_xlat76 = u_xlat77 * u_xlat32 + u_xlat9.x;
                    } else {
                        u_xlat9.xy = u_xlat8.xy * _AdditionalShadowmapSize.zw + vec2(0.5, 0.5);
                        u_xlat9.xy = floor(u_xlat9.xy);
                        u_xlat55.xy = u_xlat8.xy * _AdditionalShadowmapSize.zw + (-u_xlat9.xy);
                        u_xlat10 = u_xlat55.xxyy + vec4(0.5, 1.0, 0.5, 1.0);
                        u_xlat11 = u_xlat10.xxzz * u_xlat10.xxzz;
                        u_xlat12.yw = u_xlat11.yw * vec2(0.0408160016, 0.0408160016);
                        u_xlat10.xz = u_xlat11.xz * vec2(0.5, 0.5) + (-u_xlat55.xy);
                        u_xlat11.xy = (-u_xlat55.xy) + vec2(1.0, 1.0);
                        u_xlat57.xy = min(u_xlat55.xy, vec2(0.0, 0.0));
                        u_xlat11.xy = (-u_xlat57.xy) * u_xlat57.xy + u_xlat11.xy;
                        u_xlat57.xy = max(u_xlat55.xy, vec2(0.0, 0.0));
                        u_xlat33.xz = (-u_xlat57.xy) * u_xlat57.xy + u_xlat10.yw;
                        u_xlat11.xy = u_xlat11.xy + vec2(2.0, 2.0);
                        u_xlat10.yw = u_xlat33.xz + vec2(2.0, 2.0);
                        u_xlat13.z = u_xlat10.y * 0.0816320032;
                        u_xlat14.xyz = u_xlat10.zxw * vec3(0.0816320032, 0.0816320032, 0.0816320032);
                        u_xlat10.xy = u_xlat11.xy * vec2(0.0816320032, 0.0816320032);
                        u_xlat13.x = u_xlat14.y;
                        u_xlat13.yw = u_xlat55.xx * vec2(-0.0816320032, 0.0816320032) + vec2(0.163264006, 0.0816320032);
                        u_xlat11.xz = u_xlat55.xx * vec2(-0.0816320032, 0.0816320032) + vec2(0.0816320032, 0.163264006);
                        u_xlat11.y = u_xlat10.x;
                        u_xlat11.w = u_xlat12.y;
                        u_xlat13 = u_xlat11 + u_xlat13;
                        u_xlat14.yw = u_xlat55.yy * vec2(-0.0816320032, 0.0816320032) + vec2(0.163264006, 0.0816320032);
                        u_xlat12.xz = u_xlat55.yy * vec2(-0.0816320032, 0.0816320032) + vec2(0.0816320032, 0.163264006);
                        u_xlat12.y = u_xlat10.y;
                        u_xlat10 = u_xlat12 + u_xlat14;
                        u_xlat11 = u_xlat11 / u_xlat13;
                        u_xlat11 = u_xlat11 + vec4(-3.5, -1.5, 0.5, 2.5);
                        u_xlat12 = u_xlat12 / u_xlat10;
                        u_xlat12 = u_xlat12 + vec4(-3.5, -1.5, 0.5, 2.5);
                        u_xlat11 = u_xlat11.wxyz * _AdditionalShadowmapSize.xxxx;
                        u_xlat12 = u_xlat12.xwyz * _AdditionalShadowmapSize.yyyy;
                        u_xlat14.xzw = u_xlat11.yzw;
                        u_xlat14.y = u_xlat12.x;
                        u_xlat15 = u_xlat9.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat14.xyzy;
                        u_xlat55.xy = u_xlat9.xy * _AdditionalShadowmapSize.xy + u_xlat14.wy;
                        u_xlat11.y = u_xlat14.y;
                        u_xlat14.y = u_xlat12.z;
                        u_xlat16 = u_xlat9.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat14.xyzy;
                        u_xlat17.xy = u_xlat9.xy * _AdditionalShadowmapSize.xy + u_xlat14.wy;
                        u_xlat11.z = u_xlat14.y;
                        u_xlat18 = u_xlat9.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat11.xyxz;
                        u_xlat14.y = u_xlat12.w;
                        u_xlat19 = u_xlat9.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat14.xyzy;
                        u_xlat34.xy = u_xlat9.xy * _AdditionalShadowmapSize.xy + u_xlat14.wy;
                        u_xlat11.w = u_xlat14.y;
                        u_xlat63.xy = u_xlat9.xy * _AdditionalShadowmapSize.xy + u_xlat11.xw;
                        u_xlat12.xzw = u_xlat14.xzw;
                        u_xlat14 = u_xlat9.xyxy * _AdditionalShadowmapSize.xyxy + u_xlat12.xyzy;
                        u_xlat58.xy = u_xlat9.xy * _AdditionalShadowmapSize.xy + u_xlat12.wy;
                        u_xlat12.x = u_xlat11.x;
                        u_xlat9.xy = u_xlat9.xy * _AdditionalShadowmapSize.xy + u_xlat12.xy;
                        u_xlat20 = u_xlat10.xxxx * u_xlat13;
                        u_xlat21 = u_xlat10.yyyy * u_xlat13;
                        u_xlat22 = u_xlat10.zzzz * u_xlat13;
                        u_xlat10 = u_xlat10.wwww * u_xlat13;
                        vec3 txVec43 = vec3(u_xlat15.xy,u_xlat8.z);
                        u_xlat77 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec43, 0.0);
                        vec3 txVec44 = vec3(u_xlat15.zw,u_xlat8.z);
                        u_xlat11.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec44, 0.0);
                        u_xlat11.x = u_xlat11.x * u_xlat20.y;
                        u_xlat77 = u_xlat20.x * u_xlat77 + u_xlat11.x;
                        vec3 txVec45 = vec3(u_xlat55.xy,u_xlat8.z);
                        u_xlat55.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec45, 0.0);
                        u_xlat77 = u_xlat20.z * u_xlat55.x + u_xlat77;
                        vec3 txVec46 = vec3(u_xlat18.xy,u_xlat8.z);
                        u_xlat55.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec46, 0.0);
                        u_xlat77 = u_xlat20.w * u_xlat55.x + u_xlat77;
                        vec3 txVec47 = vec3(u_xlat16.xy,u_xlat8.z);
                        u_xlat55.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec47, 0.0);
                        u_xlat77 = u_xlat21.x * u_xlat55.x + u_xlat77;
                        vec3 txVec48 = vec3(u_xlat16.zw,u_xlat8.z);
                        u_xlat55.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec48, 0.0);
                        u_xlat77 = u_xlat21.y * u_xlat55.x + u_xlat77;
                        vec3 txVec49 = vec3(u_xlat17.xy,u_xlat8.z);
                        u_xlat55.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec49, 0.0);
                        u_xlat77 = u_xlat21.z * u_xlat55.x + u_xlat77;
                        vec3 txVec50 = vec3(u_xlat18.zw,u_xlat8.z);
                        u_xlat55.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec50, 0.0);
                        u_xlat77 = u_xlat21.w * u_xlat55.x + u_xlat77;
                        vec3 txVec51 = vec3(u_xlat19.xy,u_xlat8.z);
                        u_xlat55.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec51, 0.0);
                        u_xlat77 = u_xlat22.x * u_xlat55.x + u_xlat77;
                        vec3 txVec52 = vec3(u_xlat19.zw,u_xlat8.z);
                        u_xlat55.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec52, 0.0);
                        u_xlat77 = u_xlat22.y * u_xlat55.x + u_xlat77;
                        vec3 txVec53 = vec3(u_xlat34.xy,u_xlat8.z);
                        u_xlat55.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec53, 0.0);
                        u_xlat77 = u_xlat22.z * u_xlat55.x + u_xlat77;
                        vec3 txVec54 = vec3(u_xlat63.xy,u_xlat8.z);
                        u_xlat55.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec54, 0.0);
                        u_xlat77 = u_xlat22.w * u_xlat55.x + u_xlat77;
                        vec3 txVec55 = vec3(u_xlat14.xy,u_xlat8.z);
                        u_xlat55.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec55, 0.0);
                        u_xlat77 = u_xlat10.x * u_xlat55.x + u_xlat77;
                        vec3 txVec56 = vec3(u_xlat14.zw,u_xlat8.z);
                        u_xlat55.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec56, 0.0);
                        u_xlat77 = u_xlat10.y * u_xlat55.x + u_xlat77;
                        vec3 txVec57 = vec3(u_xlat58.xy,u_xlat8.z);
                        u_xlat55.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec57, 0.0);
                        u_xlat77 = u_xlat10.z * u_xlat55.x + u_xlat77;
                        vec3 txVec58 = vec3(u_xlat9.xy,u_xlat8.z);
                        u_xlat9.x = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec58, 0.0);
                        u_xlat76 = u_xlat10.w * u_xlat9.x + u_xlat77;
                    }
                }
            } else {
                vec3 txVec59 = vec3(u_xlat8.xy,u_xlat8.z);
                u_xlat76 = textureLod(sampler2DShadow(_AdditionalLightsShadowmapTexture, sampler_LinearClampCompare), txVec59, 0.0);
            }
            u_xlat8.x = 1.0 + (-_AdditionalShadowParams[u_xlati74].x);
            u_xlat76 = u_xlat76 * _AdditionalShadowParams[u_xlati74].x + u_xlat8.x;
            u_xlatb8.x = 0.0>=u_xlat8.z;
            u_xlatb31 = u_xlat8.z>=1.0;
            u_xlatb8.x = u_xlatb31 || u_xlatb8.x;
            u_xlat76 = (u_xlatb8.x) ? 1.0 : u_xlat76;
        } else {
            u_xlat76 = 1.0;
        }
        u_xlat8.x = (-u_xlat76) + 1.0;
        u_xlat76 = u_xlat71 * u_xlat8.x + u_xlat76;
        u_xlat75 = u_xlat75 * u_xlat76;
        u_xlat8.xyz = vec3(u_xlat75) * _AdditionalLightsColor[u_xlati74].xyz;
        u_xlat74 = dot(u_xlat2.xyz, u_xlat7.xyz);
        u_xlat74 = clamp(u_xlat74, 0.0, 1.0);
        u_xlat9.xyz = vec3(u_xlat74) * u_xlat8.xyz;
        u_xlat7.xyz = u_xlat3.xyz * u_xlat23.xxx + u_xlat7.xyz;
        u_xlat74 = dot(u_xlat7.xyz, u_xlat7.xyz);
        u_xlat74 = max(u_xlat74, 1.17549435e-38);
        u_xlat74 = inversesqrt(u_xlat74);
        u_xlat7.xyz = vec3(u_xlat74) * u_xlat7.xyz;
        u_xlat74 = dot(u_xlat2.xyz, u_xlat7.xyz);
        u_xlat74 = clamp(u_xlat74, 0.0, 1.0);
        u_xlat74 = log2(u_xlat74);
        u_xlat74 = u_xlat1.x * u_xlat74;
        u_xlat74 = exp2(u_xlat74);
        u_xlat7.xyz = vec3(u_xlat74) * _SpecColor.xyz;
        u_xlat7.xyz = u_xlat7.xyz * u_xlat8.xyz;
        u_xlat7.xyz = u_xlat9.xyz * u_xlat1.yzw + u_xlat7.xyz;
        u_xlat6.xyz = u_xlat6.xyz + u_xlat7.xyz;
    }
    u_xlat1.xyz = u_xlat4.xyz * u_xlat1.yzw + u_xlat5.xyz;
    u_xlat1.xyz = u_xlat6.xyz + u_xlat1.xyz;
    u_xlat23.x = u_xlat69 * (-u_xlat69);
    u_xlat23.x = exp2(u_xlat23.x);
    u_xlat1.xyz = u_xlat1.xyz + (-unity_FogColor.xyz);
    SV_Target0.xyz = u_xlat23.xxx * u_xlat1.xyz + unity_FogColor.xyz;
    u_xlatb23 = _Surface==1.0;
    u_xlatb23 = u_xlatb23 || u_xlatb46;
    SV_Target0.w = (u_xlatb23) ? u_xlat0.x : 1.0;
    return;
}

